import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../src/components/navbar";
import Footer from "../src/components/footer";

export default function Home() {
    return (
        <div>
            <Nav />
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="aslfjawe9irjeasi">
                <div className="nvsdiawe90-ewe">
                    <img src="/images/i1.png" />
                    <img src="/images/i2.png" />
                    <img src="/images/i3.png" />
                    <img src="/images/i4.png" />
                    <img src="/images/i5.png" />
                    <img src="/images/i6.png" />
                    <img src="/images/i7.png" />
                </div>
                <div className="container">
                    <div className="d-flex justify-content-around align-items-center cont-123 sheduewe2">
                        <div className="">
                            <img className="nidaseeb" style={{ top: 0 }} src="/images/FotoElis1.png" alt="img" />
                        </div>
                        <div>
                            <div className="ioia0ueaw0we-asd3">
                                <h4>VOCÊ,<span> MULHER,</span></h4>
                                <h5>No CONTROLE</h5>
                                <h4>da Sua <span>VIDA,</span> da Sua <span>EMPRESA,</span></h4>
                                <h4 className="djsdiaw-wr-1">dos Seus <span> GANHOS</span></h4>
                                <h4 className="djsdiaw-wr">e <span> RESULTADOS!</span></h4>
                                <div className="ooadfwoe-asdfer">
                                    <img src="/images/sgn.png" />

                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </section>

            <div className="niokfiecnn2"></div>
            <section className="bg-gry-1s2 pb-4">
                <div className="container pt-4">
                    <div className="uaier934d asdhiferrsdf">
                        <p>
                            Para Mulheres Empresárias que querem estar No Controle da sua vida, da sua empresa e dos seus resultados. Vivendo plenamente como mãe, mulher, empresária, sendo reconhecida, conquistando seus objetivos de mulher e empresária.
           </p>
                        <p>
                            E a única maneira de ter tudo é aprendendo a colocar “Energia Certa no Lugar Exato”, desenvolvendo Alta Performance para estar No Controle!
           </p>

                    </div>
                    <div>

                    </div>


                    <div className="row mt-3">
                        <div className="col-md-6">
                            <div>
                                <div className="nadvso0e-awds">
                                    <p>Mulher, Assista ao MANIFESTO {`>>>>>`}</p>
                                </div>
                                <div className="asdhiferr-1212">
                                    <h5>Elis Ferraz</h5>
                                    <h5>Empresária | Mentora</h5>
                                    <div className="mt-3">
                                        <p>Eu, como a maioria das mulheres, fui educada para ser qualquer coisa, menos empresária e bem-sucedida!</p>
                                        <p>Infelizmente, tive que aprender do pior jeito possível como conquistar uma vida plena, sendo mãe, empresária, mulher e reconhecida.</p>
                                        <p>Infelizmente, tive que aprender do pior jeito possível como conquistar uma vida plena, sendo mãe, empresária, mulher e reconhecida.</p>
                                        <p>E foi apenas diante de um câncer em estágio avançado causado por estresse, frustração e falta de cuidado comigo mesma que tive um encontro com a verdade.</p>

                                    </div>
                                    <div className="mt-3">
                                        <p>A verdade de que eu não tinha que abrir mão das coisas que eram importantes. Eu não tinha que escolher entre a empresa e minha família. Eu não tinha que ser produtiva e não tinha que seguir os modelos de produtividade criada para homens e por homens. Eu apenas tinha que fazer as coisas do “Jeito Mulher”. E essa verdade me fez ver que a única maneira de ser mulher e empresária bem sucedida é estando No Controle da minha vida, aprendendo a ser uma pessoa de alta performance colocando “energia certa no lugar exato”.</p>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div className="col-md-6">
                            <div className="asdfidjer-sd"></div>










                            <div className="nsdairejrog1sd mt-4">
                                <div className="xkdnidr11">
                                    <div>
                                        <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                                    </div>
                                    <div className="d-flex align-items-center jfdosa-sais89sd">
                                        <div>
                                            <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                                            <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                                        </div>
                                        <img className="eruwherhd" src="/images/next.png" />
                                        <div className="asdfiher-sdw sdfjdecdr">
                                            <p className="sdrehidf">EU QUERO</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div className="niokfiecnn2"></div>
            <section className="bg-gry-1s3">
                <div className="container">
                    <div className="nsdavosdf-ewjosie">
                        <div>
                            <img className="w-100 niasdfh-ehsahdwe" src="/images/avt1.png" />
                        </div>
                        <div className="nisdafosj-429se">
                            <h5>Os<span> 3 Pilares</span></h5>
                            <h5 className="nsdafsid-dsnfuser-1">de<span> Negócios</span></h5>
                            <h4 className="nsdafsid-dsnfuser">Prósperos</h4>
                        </div>
                        <div>
                            <img className="w-100 niasdf-3erhasf" src="/images/websd1.png" />

                        </div>

                    </div>
                </div>
            </section>
            <div className="niokfiecnn2"></div>
            <section className="o2wqsasnw  pb-5">
                <div className="container">
                    <h5 className="niasde0-ewds23">Programas de MENTORIA</h5>
                    <div className="ojasd0-39uhs2s1" >
                        <div className="oiouqw-eqwdsw">
                            <div className="oiouqw-eqwdsw-1">
                                <img className="w-100" src="/images/cntrl.png" />
                            </div>
                            <div className="oiouqw-eqwdsw-2">
                                <p className="oiouqw-eqwdsw-3">Programa de Mentoria para VOCÊ Mulher, estar No CONTROLE da sua vida, não tendo mais que abrir mão de tudo o que é importante, vivendo plenamente como: mãe, empresária, mulher, sendo reconhecida na carreira e nos negócios, desenvolvendo Alta Performance com o uso do PLANNER, promovendo mudanças de dentro para fora, acelerando seus resultados e lhe proporcionando um novo estilo de vida.</p>
                                <div className="oiouqw-eqwdsw-4">
                                    <button className="btn oiouqw-eqwdsw-5">QUERO SABER...</button>
                                </div>
                            </div>
                        </div>
                        <div className="oiouqw-eqwdsw">
                            <div className="oiouqw-eqwdsw-1">
                                <img className="w-100" src="/images/Alavancar.png" />
                            </div>
                            <div className="oiouqw-eqwdsw-2">
                                <p className="oiouqw-eqwdsw-3">Programa de Mentoria Especializado para a Mulher Empresária ALAVANCAR sua empresa, se colocando No Controle para desenvolver pessoas e equipes auto gerenciáveis, tornando Sua Empresa uma Fonte de Renda. Utilizando o PLANNER para acelerar seus resultados, possibilitando liberdade de tempo, dinheiro e bem estar como empresária.
</p>
                                <div className="oiouqw-eqwdsw-4">
                                    <button className="btn oiouqw-eqwdsw-5">QUERO SABER...</button>
                                </div>
                            </div>
                        </div>

                        <div className="oiouqw-eqwdsw">
                            <div className="oiouqw-eqwdsw-1">
                                <img className="w-100" src="/images/Bhj.png" />
                            </div>
                            <div className="oiouqw-eqwdsw-2">
                                <p className="oiouqw-eqwdsw-3">Programa de Mentoria com Foco no Desenvolvimento de Mentalidade Estratégica Comercial. Com o objetivo de posicionar a mulher empresária no controle dos ganhos e resultados desenvolvendo inteligência comercial: funis de venda, gerar impacto emocional com storytelling e maior conexão com os clientes, posicionamento e estratégias on-line | off-line, esteira de venda e treinamento da equipe.
</p>
                                <div className="oiouqw-eqwdsw-4">
                                    <button className="btn oiouqw-eqwdsw-5">QUERO SABER...</button>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>

            <div className="niokfiecnn2"></div>

            <section className="aslfjawe9irjeasi123x1">
                <h1 className="nbbjdsiwe90d">
                    HIGH PERFORMANCE PLANNER
                </h1>
                <div className="nkdsife-wqej21">
                    <div className="nkdsife-wqej21-1">
                        <div className="nkdsife-wqej21-2">
                            <h5>O PLANNER</h5>
                            <div>
                                <p>É o primeiro Planner no mundo com esta proposta de Estilo de Vida de Alta Performance.</p>
                                <p>O High Performance Planner é um novo conceito e um novo estilo de vida de pessoas que querem estar No Controle. Foi desenvolvido para que, com menos esforço se tenha resultados extraordinários, promovendo Alta Performance e acelerando resultados. </p>
                                <p>Um novo conceito baseado no que há de mais atual na ciência da mente que, através de ações simples, práticas e objetivas promove a mudança de mentalidade criando uma experiência única reprogramando sua mente para vencer.</p>
                            </div>
                        </div>
                        <div className="d-flex justify-content-end">
                            <button className="btn bvasdue-drw">EU QUERO O PLANNER</button>
                        </div>
                    </div>

                </div>
            </section>
            <div className="niokfiecnn2"></div>

            <section className="isdfderf">
                <div className="container">
                    <div className="zxnvuer d-flex">
                        <div className="xjfudfsdi iaotjedsjofsdf">
                            <h1 className="skd-sdjfe">Eu</h1>
                            <h2 className="skd-sdjfe">ACREDITO</h2>
                            <h2 className="skd-sdjfe" style={{ fontSize: 56 }}>Em VOCÊ</h2>
                        </div>
                        <div className="nsdjfrihf">
                            <h1>Eu ACREDITO</h1>
                            <p>
                                Nas pessoas. Sei que elas podem mudar seus resultados se mudarem
                                o jeito de pensar.
        </p>
                            <p>
                                Acredito que, a transformação de uma pessoa, pode significar
                                relacionamentos mais bem sucedidos, filhos mais fortes e
                                famílias mais unida.
        </p>
                            <p>
                                Acredito na reprogramação da mente baseada na ciência. E ela
                                pode ser conquistada com pequenas ações diárias.
        </p>
                            <p>
                                Acredito que o mundo se torna um lugar melhor quando ajuda
                                pessoas a transformarem suas vidas.
        </p>
                            <p>
                                Acredito em tudo isso, porque tive que por a prova todas essas
                                crenças diante dos desafios que
        </p>
                            <p>
                                enfrentei ao longo da minha vida. Estar No Controle foi o que me
                                garantiu o sucesso e o que tem garantido o sucesso de todos os
                                que vivem essa experiência.
        </p>
                            <h3>ELIS FERRAZ</h3>
                        </div>
                    </div>
                    <div className="asjdiswjecsd">
                        <div>
                            <div>
                                <h1 className="askdhasjwe-sdijw">

                                    Um Jeito <span className="cksjdf">DIFERENTE</span> de
            <span className="cksjdf sdkjeirfd"> PENSAR</span>,
          </h1>
                                <h1 className="askdhasjwe-sdijw">
                                    <span className="cksjdf sdkjeirfd">ESTRUTURAR</span> e
            <span className="cksjdf sdkjeirfd"> Ganhar MAIS</span>
                                </h1>
                                <h1 className="askdhasjwe-sdijw">

                                    na <span className="sdkjeirfd">VIDA</span> e nos
            <span className="sdkjeirfd"> NEGÓCIOS </span>
                                </h1>
                                <h1 className="askdhasjwe-sdijw">
                                    Estando <span className="cksjdf sdkjeirfd">NO CONTROLE!</span>
                                </h1>
                            </div>
                            <div className="mgt65">
                                <p className="asjfiser">
                                    Com 17 anos de experiência, tendo passado por mais de 280 empresas no Brasil e Estados Unidos, de diversos tamanho e segmento. Ajudando mulheres e empresários a estarem No Contorle da sua vida, da sua empresa e dos seus ganhos, desenvolverem Alta Performance, tornando suas empresas Fonte de Renda. Mostrando como desenvolver mentalidade estratégica comercial para gerar maior conexão com clientes potenciais transformando mais oportunidades em negócios.
          </p>
                                <p className="asjfiser">
                                    Elis Ferraz é autora do High Performance Planner, único no mundo. Desenvolveu vários programas de treinamento como 6 Super Habilidades (implementado em multinacionais), 10em1 - 10 anos de Faturamento em 1.
É uma grande estudiosa e entusiasta nas ciências da mente para mudança de mentalidade. </p>
                            </div>
                        </div>
                        <div>
                            <img className="ksdjiekfdf" src="/images/websd.png" />
                        </div>
                    </div>
                </div>
            </section>
            <div className="niokfiecnn2"></div>
            <section className="bgpajsfie pt-5 pb-4">
                <div className="container">
                    <div className="xjbzeefb">
                        <h1>NÓS ACREDITAMOS em Elis Ferraz!</h1>
                        <div className="klgjt">
                            <div className="xjbzeefb m-3">
                                <div className="weonksfi">
                                    <img src="/images/scr.png" />
                                    <div className="airyew3oif">
                                        <p>Rachel França</p>
                                        <span>Empresária | Arquiteta</span>
                                    </div>
                                </div>
                                <p className="sajjksdue">
                                    “Aprender a atitude certa, desenvolvendo Alta Performance me
                                    fez decolar na vida!”
                </p>
                            </div>

                            <div className="xjbzeefb m-3">
                                <div className="weonksfi">
                                    <img src="/images/scr.png" />
                                    <div className="airyew3oif">
                                        <p>Isis Leal</p>
                                        <span>Empresária | Teatro</span>
                                    </div>
                                </div>
                                <p className="sajjksdue">
                                    “A mudança de Mentalidade é a chave para alavancar na vida e
                                    nos negócios!”
                </p>
                            </div>

                            <div className="xjbzeefb m-3">
                                <div className="weonksfi">
                                    <img src="/images/scr.png" />
                                    <div className="airyew3oif">
                                        <p>Mel Domezi</p>
                                        <span>Empresária</span>
                                    </div>
                                </div>
                                <p className="sajjksdue">
                                    “A transformação do meu jeito de pensar, me fez conquistar
                                    muito, incluive fontes de renda!”
                </p>
                            </div>
                        </div>
                        <div className="nsdairejrog1sd mt-5">
                            <div className="xkdnidr11sds">
                                <div>
                                    <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                                </div>
                                <div className="d-flex align-items-center">
                                    <div>
                                        <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                                        <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                                    </div>
                                    <img className="eruwherhd" src="/images/arwcrl.png" />
                                    <div className="asdfiher-sdw ">
                                        <p className="sdrehidf">EU QUERO</p>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </section>
            <div className="niokfiecnn2"></div>
            <section className="o2wqsasnw pt-4 pb-4">
                <div className="container">
                    <div className="snafjrjifjg">
                        <div className="row ojsdakwqpd">
                            <div className="col-md-6">
                                <div>
                                    <img className="nisetje" src="/images/fotoelis.png" />
                                    <div className="jfaewisf">
                                        <p className="agdhgegg">ELIS FERRAZ</p>
                                        <div className="sdfgjiet"></div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-md-6">
                                <div className="czxbvdsuf">
                                    <h1>Quem</h1>
                                    <h6>será sua </h6>
                                    <h2>MENTORA e</h2>
                                    <h2>Treinadora ?</h2>
                                </div>
                            </div>
                        </div>
                        <div>
                            <p className="dfjaier">
                                Elis é empresária há mais de 17 anos. Passou por mais de 280
                                empresas atuando em estratégias, gestão comercial, contratação,
                                desenvolvimento de pessoas e de mentalidade de alta performance.
              </p>
                        </div>

                        <div className="gsdjhrgy">
                            <h2>EMPRESÁRIA</h2>
                            <div className="d-flex asfnsoirr3-23">
                                <span>+</span>
                                <h5> 17 anos de experiência</h5>
                            </div>
                        </div>
                        <div className="gsdjhrgy asfosjr-seew">
                            <h2>MENTORA E TREINADORA</h2>
                            <div className="d-flex asfnsoirr3-23">
                                <span>+</span>
                                <h5> 2.000 pessoas Treinadas e mais de 280 empresas </h5>
                            </div>
                        </div>
                        <div className="gsdjhrgy asfosjr-seew">
                            <h2>Author</h2>
                            <div className="m-0 d-flex asfnsoirr3-23">
                                <span className="nsirefg">+</span>
                                <h5>
                                    15 programas de treinamentos, entre eles: 10em1 - 10 anos de
                                    Faturamento em 1; 6 Super Habilidades - Influenciar | Escolher
                                    | Escutar | Conversar | Negociar | Liderar; Programas de
                                    Mentoria para empresas e empresários - No Controle | Alavancar
                                    | Ganhar Mais.
                </h5>
                            </div>
                        </div>
                    </div>
                    <div className="cmdsfnief">
                        <div>
                            <img className="kndgofdg" src="/images/cloud.png" />
                            <img className="sfdghidgr" src="/images/exam.png" />
                        </div>
                        <div className="ariothge">
                            <div className="asfmsrh9wasf">
                                <div className="znxiwebwwf">
                                    <p className="sandsket">INSCREVER-ME AGORA NA MENTORIA</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div className="niokfiecnn2"></div>


            <section className="bg-gry-1s pt-4 pb-4">
                <div className="container">
                    <div>
                        <h1 className="ndsajfsdfer">ELIS Pra VOCÊ!</h1>
                        <div className="">
                            <div className="nsdkfhe sfeoireork">
                                <img src="/images/port/av2.jpg" />
                                <img src="/images/port/av3.jpg" />
                                <img src="/images/port/av4.jpg" />
                                <img src="/images/port/av5.jpg" />
                                <div className="asjdiwefer">
                                    <p className="sdjaojer"> Vídeo Minha História</p>
                                </div>
                            </div>
                        </div>

                        <div className="">
                            <div className="nsdkfhe sfeoireork">
                                <img src="/images/port/av6.jpg" />
                                <img src="/images/port/av7.jpg" />
                                <img src="/images/port/av8.jpg" />
                                <img src="/images/port/av9.jpg" />
                                <div className="asjdiwefer">
                                    <p className="sdjaojer"> Vídeo Sou Mulher Série</p>
                                </div>
                            </div>
                        </div>

                        <div className="">
                            <div className="nsdkfhe sfeoireork">
                                <img src="/images/port/av10.jpg" />
                                <img src="/images/port/av11.jpg" />
                                <img src="/images/port/av12.jpg" />
                                <img src="/images/port/av13.jpg" />
                                <div className="asjdiwefer">
                                    <p className="sdjaojer"> Vídeo No Controle Série</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="sdnserr i9ehdh283dcd">
                        <img className="sadhee bnjhxerr" src="/images/port/av1.png" />
                        <div className="nsakdhe3">
                            <h1 className="sceirjfg">EU, O PLANNER e uma Vida No CONTROLE</h1>

                            <p>
                                Você já pensou o que te faz realizar uma grande mudança?
              </p>
                            <p>Para
                mim, foi estar entre a vida e a morte.</p>
                            <p>
                                Me tornei uma mulher bem sucedida, mas quando vieram os filhos e
                                as responsabilidades com a família aumentaram, passei a ter que
                                escolher entre ser empresária e ter uma família. Foram os anos
                                mais difíceis de minha vida!
              </p>
                            <p>
                                O problema não era ter que conciliar a empresa e a família, era
                                conciliar essas duas coisas que eu considerava uma prioridade
                                tentando ser produtiva ao invés de estratégica sendo uma mulher
                                de Alta Performance.
              </p>

                            <p>
                                Eu aprendi a estar No Controle da minha vida deixando de usar os
                                modelos de produtividade criado para homens e por homens. Passei
                                a adotar uma nova abordagem, fazendo as coisas do jeito mulher,
                                aprendendo a colocar “Energia Certa no Lugar exato”. E dessa
                                forma, acelerei meus resultados e passei a viver uma vida de
                                muitas conquistas.
              </p>
                            <p>A vida é um espelho que me reflete e eu gosto do que vejo!</p>
                        </div>
                    </div>
                </div>
            </section>













            <div className="niokfiecnn2"></div>

            <section className="bgpajsfie pt-4 pb-4">
                <div className="container">
                    <div className="sdanierhser">
                        <h1 className="dsnierg">O MANIFESTO</h1>
                        <div className="asdnfsdi"></div>

                        <div className="nsdairejrog1sd mt-5">
                            <div className="xkdnidr11sds">
                                <div>
                                    <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                                </div>
                                <div className="d-flex align-items-center">
                                    <div>
                                        <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                                        <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                                    </div>
                                    <img className="eruwherhd" src="/images/arwcrl.png" />
                                    <div className="asdfiher-sdw ">
                                        <p className="sdrehidf">EU QUERO</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>
            <div className="niokfiecnn2"></div>
            <section className="sdafisrjenfd pt-4 pb-4">
                <div className="container">
                    <div className="d-flex flex-wrap serhuisdfg justify-content-end">
                        <img src="/images/brd/Copia de 1.png" />
                        <img src="/images/brd/Copia de 2.png" />
                        <img src="/images/brd/Copia de 3.png" />

                    </div>
                    <div className="d-flex flex-wrap justify-content-center">
                        <img src="/images/brd/Copia de 4.png" />
                        <img src="/images/brd/Copia de 5.png" />
                        <img src="/images/brd/Copia de 6.png" />
                        <img src="/images/brd/Copia de 7.png" />
                        <img src="/images/brd/Copia de 8.png" />
                        <img src="/images/brd/Copia de 9.png" />
                    </div>
                    <div className="d-flex flex-wrap justify-content-center">
                        <img src="/images/brd/Copia de 10.png" />
                        <img src="/images/brd/Copia de 11.png" />
                        <img src="/images/brd/Copia de 12.png" />
                        <img src="/images/brd/Copia de 13.png" />
                        <img src="/images/brd/Copia de 14.png" />
                        <img src="/images/brd/Copia de 15.png" />
                    </div>
                    <div className="d-flex flex-wrap justify-content-center">
                        <img src="/images/brd/Copia de 16.png" />
                        <img src="/images/brd/Copia de 17.png" />
                        <img src="/images/brd/Copia de 18.png" />
                        <img src="/images/brd/Copia de 19.png" />
                        <img src="/images/brd/Copia de 20.png" />
                        <img src="/images/brd/Copia de 21.png" />
                    </div>
                    <div className="d-flex flex-wrap justify-content-center">
                        <img src="/images/brd/Copia de 21.png" />
                        <img src="/images/brd/Copia de 22.png" />
                        <img src="/images/brd/Copia de 23.png" />
                        <img src="/images/brd/Copia de 24.png" />
                        <img src="/images/brd/Copia de 25.png" />
                        <img src="/images/brd/Copia de 26.png" />
                    </div>
                    <div className="d-flex flex-wrap justify-content-center">
                        <img src="/images/brd/Copia de 27.png" />
                        <img src="/images/brd/Copia de 28.png" />
                        <img src="/images/brd/Copia de 29.png" />
                        <img src="/images/brd/Copia de 30.png" />
                        <img src="/images/brd/Copia de 31.png" />
                        <img src="/images/brd/Copia de 32.png" />
                    </div>
                </div>
            </section>
            <div className="niokfiecnn2"></div>

            <Footer hasNav={true} />
        </div>
    );
}
