import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../src/components/navbar";
import Footer from "../src/components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="nkasjuwrk">

        <h1>        Não Seja Produtivo.
        Tenha ALTA Performance!
</h1>

      </section>
      <section className="aslfjawe9irjeasi123">
        <div className="container">
          <div className="d-flex justify-content-around align-items-center cont sheduewe2">
            <div className="">
              <img className="nidaseeb" src="/images/FotoElis1.png" alt="img" />
            </div>
            <div className="">
              <div className="nais3or9der">
                <h1 className="asoenfmdr213">SEMANA de</h1>
                <h1 className="iojsdfief">MENTORIA</h1>
                <h1 className="lsdiamfdofe">No CONTROLE</h1>

                <p className="naisdneffds121">

                  <span>Aprenda como</span> desenvolver <span>Mentalidade </span> de <span>Alta Performance</span> para estar <span>No</span>

                </p>
                <p className="naisdneffds121">
                  <span>Controle</span> da sua <span>Vida,</span> da sua <span>Empresa,</span> dos seus <span>Ganhos e Resultados.</span>
                </p>
                <h3 className="miewrr3">
                  01 Junho | Terça | 19:30
               </h3>
                <div className="weasfsdfjisdfj">
                  <p>QUERO PARTICIPAR AGORA</p>
                </div>
              </div>
            </div>

          </div>

        </div>
      </section>

     <section className="ksnduerfe">
      <div className="container">
      <div className="nalsdfasf">
         <div className="nscsinisdfdf">
           <div className=""><p className="nzsifasonas">100% OnLINE</p></div>
           <div>
             <img className="insdfjseer sanskfnsdfe" src="/images/cr.png"/>
           </div>
         </div>
         <div className="iansodhawe">
           <h1>Você <span>No CONTROLE</span> da </h1>
           <h1>Sua VIDA, da Sua EMPRESA, </h1>
           <h1>dos Seus GANHOS </h1>
           <h1>e RESULTADOS!</h1>
         </div>
         <div className="nscsinisdfdf">
         <div>
             <img className="insdfjseer1" src="/images/cr1.png"/>
           </div>
           <div className=""><p className="nzsifasonas">100% Gratuito</p></div>
           
         </div>      </div>
    

      </div>
       </section>
       <div className="niokfiecnn2"></div>

    <section className="niashfasoiewicxzc">
      <div className="container">
      <div className="row">
      <div className="col-md-5">
          <div>
            <div className="nacsdifewee">
              <p>PROGRAMAÇÃO</p>
            </div>
            <div className="nsdouwewncdr2">
              <h3>SEG</h3>
              <div className="ijwe923c2"></div>
              <p>Ferramenta de Avaliação
de Produtividade

</p>
            </div>

            <div className="nsdouwewncdr2">
              <h3>TER</h3>
              <div className="ijwe923c2 "></div>
              <p className="mr-9as823">MENTORIA <span>ao VIVO</span>
19:30



</p>
            </div>
            <div className="nsdouwewncdr2">
              <h3>QUA</h3>
              <div className="ijwe923c2"></div>
              <p>Ferramenta de Avaliação de Performance e Autoimagem



</p>
            </div>
            <div className="nsdouwewncdr2">
              <h3>QUI</h3>
              <div className="ijwe923c2 "></div>
              <p className="mr-9as8231">MENTORIA <span>ao VIVO</span>
19:30



</p>
            </div>
            <div className="nsdouwewncdr2">
              <h3>SEX</h3>
              <div className="ijwe923c2"></div>
              <p>Vídeo Aulas para aplicar as
Ferramentas de Avaliação




</p>
            </div>
          </div>
        </div>
        <div className="col-md-7">

       <div className="niasdfjoer">
       <img className="ojsoeerr" src="/images/stm.png"/>
          <div className="nicasehrcnd">

          </div>
          <div className="uabsnuje">
            <p>QUERO PARTICIPAR AGORA</p>
          </div>
       </div>
        </div>
     
      </div>
      </div>
    </section>
    <div className="niokfiecnn2"></div>

    <section className="esfhdjfsje1 pb-4">
        <div className="d-flex msdjnjeber">
          <h1 className="asdfnjk3rdfge34">3</h1>
          <div className="nsareur">
            <h2 className="asdf3jirsekg3">Motivos</h2>
            <h2 className="eirddsage iieorhjofd">PARA VOCÊ INICIAR</h2>
            <h2 className="enndgsdaer hidferifer">A JORNADA DE</h2>
            <h2 className="iiwefhefsw3">Mudança de MENTALIDADE</h2>
          </div>
        </div>
      <h1 className="ojhasd9q1">Para Ter ALTA PERFORMANCE.</h1>
        <div className="nasklfnawrfg ojs9022isa">
          <div className="nakskfawjrojasfg">
            <img className="bsjdfsert" src="/images/trgbig.png" />
            <div className="jfsdkljrt iwje9we023">
              <p>Você é o que você pensa.</p>
              <p><span>Se você não mudar</span> sua mentalidade, vai continuar</p>
              <p>
                <span>tendo essa vida</span> que você
                <span>já não quer mais.</span>
              </p>
            </div>
          </div>
          <div className="nakskfawjrojasfg">
            <img className="bsjdfsert" src="/images/trgbig.png" />
            <div className="jfsdkljrt iwje9we023">
              <p>
                Essa é a <span>única maneira</span> de estar No Controle.
              </p>
              <p>
                A verdade é que <span>se você não está no controle</span>
              </p>
              <p>
                da sua vida, <span>então você está sendo controlada.</span>
              </p>
            </div>
          </div>
          <div className="nakskfawjrojasfg">
            <img className="bsjdfsert" src="/images/trgbig.png" />
            <div className="jfsdkljrt iwje9we023">
              <p>
                <span>Ter um estilo de vida</span> de
                <span>Alta Performance é</span>
              </p>
              <p>
                o que <span>pessoas inteligentes fazem.</span>
              </p>
              <p>Você pode escolher não fazer a mentoria por medo </p>
              <p>de arriscar... Mas se não arriscar por tão pouco, nunca</p>
              <p>saberá como é estar do outro lado.</p>
            </div>
          </div>
        </div>

        <div className="nsdairejrog mt-5">
          <div className="asndfiwhsefgg12">
            <p>QUERO PARTICIPAR AGORA</p>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="o2wqsasnw pt-4 pb-4">
        <div className="container">
          <div className="snafjrjifjg">
            <div className="row">
              <div className="col-md-6">
                <div>
                  <img className="nisetje" src="/images/fotoelis.png" />
                  <div className="jfaewisf">
                    <p className="agdhgegg">ELIS FERRAZ</p>
                    <div className="sdfgjiet"></div>
                  </div>
                </div>
              </div>
              <div className="col-md-6">
                <div className="czxbvdsuf">
                  <h1>Quem</h1>
                  <h6>será sua </h6>
                  <h2>MENTORA e</h2>
                  <h2>Treinadora ?</h2>
                </div>
              </div>
            </div>
            <div>
              <p className="dfjaier">
                Elis é empresária há mais de 17 anos. Passou por mais de 280
                empresas atuando em estratégias, gestão comercial, contratação,
                desenvolvimento de pessoas e de mentalidade de alta performance.
              </p>
            </div>

            <div className="gsdjhrgy">
              <h2>EMPRESÁRIA</h2>
              <div className="d-flex asfnsoirr3-23">
                <span>+</span>
                <h5> 17 anos de experiência</h5>
              </div>
            </div>
            <div className="gsdjhrgy asfosjr-seew">
              <h2>MENTORA E TREINADORA</h2>
              <div className="d-flex asfnsoirr3-23">
                <span>+</span>
                <h5> 2.000 pessoas Treinadas e mais de 280 empresas </h5>
              </div>
            </div>
            <div className="gsdjhrgy asfosjr-seew">
              <h2>Author</h2>
              <div className="m-0 d-flex asfnsoirr3-23">
                <span className="nsirefg">+</span>
                <h5>
                  
                  15 programas de treinamentos, entre eles: 10em1 - 10 anos de
                  Faturamento em 1; 6 Super Habilidades - Influenciar | Escolher
                  | Escutar | Conversar | Negociar | Liderar; Programas de
                  Mentoria para empresas e empresários - No Controle | Alavancar
                  | Ganhar Mais.
                </h5>
              </div>
            </div>
          </div>
          <div className="cmdsfnief">
            <div>
              <img className="kndgofdg" src="/images/cloud.png" />
              <img className="sfdghidgr" src="/images/exam.png" />
            </div>
            <div className="ariothge">
              <div className="asfmsrh9wasf">
                <div className="znxiwebwwf">
                  <p className="sandsket">QUERO PARTICIPAR AGORA</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie pt-4 pb-4">
        <div className="container">
          <div className="sdanierhser">
            <h1 className="dsnierg">O MANIFESTO</h1>
            <div className="asdnfsdi"></div>

            <div className="nsdairejrog1sd mt-5">
              <div className="xkdnidr213">
                <div className="d-flex flex-column">
                  <p className="dsfhkuer213 text-center dsfjoaspduhkuer213">PARTICIPAR AGORA</p>
                </div>
                <div className="asdfiher-sdw">
                  <p className="sdrehidf">EU QUERO</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <Footer hasNav={false}/>

     </div>
  );
}
