import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../src/components/navbar";
import Footer from "../src/components/footer";

export default function Home() {
  return (
    <div>
      <Nav />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="aslfjawe9irjeasi">
        <div className="container">
          <div className="d-flex justify-content-around align-items-center cont sheduewe2">
            <div className="sdfajiow39weiw">
              <img src="/images/FOTO Banner NO CONTROLE.png" className="yhiw9e33d" alt="img" />
            </div>
            <div className="">
              <div className="asdh83udashn3e">
                <div className="asd8quen9asdjmw">
                  <div className="asn9woewa092ojkaskd">
                    <h2 className="">MENTORIA</h2>
                  </div>
                </div>
                <h1 className="jids0jf0ef">No CONTROLE</h1>
                <p className="sdfjeirere">Você, No Controle da Sua VIDA!</p>
                <div className="ascawuieda8s9h3">
                  <img
                    className="sadasascawuieda8s9h3"
                    src="/images/sgn.png"
                    alt="img"
                  />
                </div>
              </div>
            </div>
            <div>
              <img src="/images/cntrl.png" alt="img" />
            </div>
          </div>
          <div>
            <h5 className="sdeirjeoirf">
              A vida, nada mais é do que um espelho que reflete você!
            </h5>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bg-gry pb-4">
        <div className="container pt-4">
          <div className="uaier934d asdhiferrsdf">
            <p className="ojiw9sdawev">
              Se a vida é um espelho que reflete você... Você está gostando do
              que vê?
            </p>
            <p className="ojiw9sdawev">
              NO CONTROLE é um Programa de Mentoria para você, que não está
              satisfeita com seus resultados, que deseja ser plena como mulher,
              empresaria, sendo reconhecida e tendo seus objetivos de vida
              realizados.E a única maneira de fazer isso é estando No Controle,
              é fazendo as coisas do “Jeito Mulher”, aprendendo a ter Alta
              Performance ao invés de tentar ser produtiva.
            </p>
          </div>
          <div className="row">
            <div className="col-md-6">
              <div>
                <div>
                  <h4 className="asdnkdffd">
                    Programa de Mentoria No CONTROLE 4.0
                  </h4>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/diary.png" />
                  <p className="masdkere">
                    Planner Exclusivo: Enviado para sua casa
                  </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/target.png" />
                  <p className="masdkere">
                    Foco no Desenvolvimento de Alta Performance para te colocar
                    No Controle da sua vida.
                  </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/rocket.png" />
                  <p className="masdkere">
                    É o único Programa de Mentoria que utiliza o High
                    Performance PLANNER. Um Acelerador de Resultados para
                    desenvolver novos hábitos, habilidades e crenças promovendo
                    mudança de mentalidade.
                  </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/help.png" />
                  <p className="masdkere">
                    A mentoria é super interativa. Você recebe conteúdo, faz
                    atividades em grupo, tira suas duvidas e aprende a vencer
                    sabotadores com várias técnicas que usa fisiologia e
                    gatilhos.
                  </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/laddar.png" />
                  <p className="masdkere">
                    Um Método que treina competências específicas para sua mente
                    ter foco no objetivo, vencer a procrastinação, se tornar
                    centrado, desenvolvendo alta performance antes de
                    produtividade direcionando sua mente para ações vitais e não
                    em tarefas.
                  </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/brain.png" />
                  <p className="masdkere">
                    Promove a Mudança de Mentalidade através de práticas simples e diárias baseadas na ciência para reprogramar a mente com mais velocidade – Hora de Ouro.

                  </p>
                </div>
              </div>
            </div>
            <div className="col-md-6">
              <div className="asdfidjer-sd"></div>

              <div className="nsdairejrog1sd mt-5">
                <div className="xkdnidr11">
                  <div>
                    <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                  </div>
                  <div className="d-flex align-items-center">
                    <div>
                      <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                      <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                    </div>
                    <img className="eruwherhd" src="/images/next.png" />
                    <div className="asdfiher-sdw sdfjdecdr">
                      <p className="sdrehidf">EU QUERO</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="o2wqsasnw pt-4 pb-4">
        <div className="container">
          <div className="row">
            <div className="col-md-9">
              <div>
                <div className="asnasijweiasfbs-nau">
                  <img className="qjsdifef12123" src="/images/stm.png" />
                  <div>
                    <h4 className="asncoajew9osf">VOCÊ, finalmente,</h4>
                    <h4 className="asdi9jasf12f lniahe0i3">
                      <span>No CONTROLE</span>
                    </h4>
                    <h4 className="erudshfsdf lniahe0i3123">da Sua Vida!</h4>
                  </div>
                </div>
                <div className="nasdkfo-sfeier">
                  <div>
                    <p className="asfniajdwasw ihsdfww2032">
                      COMO FUNCIONA O PROGRAMA DE MENTORIA?
                    </p>
                    <p className="asfaojfsi3e ihsdfww20321">
                      Ao adquirir o Programa de Mentoria 4.0 você...
                    </p>
                  </div>
                  <div>
                    <div className="d-flex">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                        Recebe os 2 Planners na sua casa - 1 para cada semestre.
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                        Aprende passo a passo como usar o planner para construir
                        um estilo de vida de alta performance, treinando sua
                        mente para desenvolver competências e habilidades
                        específicas com práticas simples e objetivas.
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                        É inserido no Grupo Exclusivo para ter acesso a
                        conteúdos, ferramentas e testes para autoavaliação.
                        Responde a um questionário de expectativas.
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                        Recebe um link para participar das mentorias que são
                        online, ao vivo e acontecem 1 vez por semana durante 3
                        meses - 90 dias, 90 minutos por encontro.
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                        Você pode e deve participar tirando dúvidas diretamente
                        comigo, Elis Ferraz, durante as mentorias ou com a
                        equipe de co-facilitadores.
                      </p>
                    </div>
                  </div>
                </div>

                <div className="d-flex naskerer">
                  <img
                    className="oihioajwe9cqw"
                    src="/images/avt1.png"
                  />
                  <div className="hriehudfdg">
                    <p className="asfniajdwasw">O PLANNER</p>
                    <p className="eowujsdifhsdg">
                      EDIÇÃO LUXUOSA, ACABAMENTO PREMIUM, COLORIDO COM CAPA
                      DURA.
                    </p>
                    <p className="nasidfasdnsfndsje">
                      É o primeiro Planner no mundo com esta proposta de Estilo
                      de Vida de Alta Performance.
                    </p>
                    <p className="nasidfasdnsfndsje">
                      O High Performance Planner é um novo conceito e um novo
                      estilo de vida de pessoas que querem estar No Controle.
                      Foi desenvolvido para que, com menos esforço se tenha
                      resultados extraordinários, promovendo Alta Performance e
                      acelerando resultados.
                    </p>
                    <p className="nasidfasdnsfndsje">
                      Um novo conceito baseado no que há de mais atual na
                      ciência da mente que, através de ações simples, práticas e
                      objetivas promove a mudança de mentalidade criando uma
                      experiência única reprogramando sua mente para vencer.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-3">
              <div className="mt-5">
                <div className="ndskfiere">
                  <img src="/images/key.png" />
                  <div className="">
                    <p className="weorweietdf">
                      3 meses,12 mentorias, 90 dias, 90 minutos cada.
                    </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/face.png" />
                  <div className="">
                    <p className="weorweietdf">Mentoria Ao Vivo e Interativa</p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <div>
                    <img src="/images/cam.png" />
                    <img src="/images/mic.png" />
                  </div>

                  <div className="">
                    <p className="weorweietdf">Vídeo Aulas e PodCast</p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <img src="/images/booksm.png" />
                  <div className="">
                    <p className="weorweietdf">
                      Testes de Comportamento, PDFs e Ferramentas
                    </p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <img src="/images/chat.png" />
                  <div className="">
                    <p className="weorweietdf">
                      Equipe de Suporte e encontros comigo.
                    </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/lock.png" />
                  <div className="">
                    <p className="weorweietdf">
                      Grupo Exclusivo de Mentoria, atividade dupla.
                      complementares
                    </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/qr.png" />
                  <div className="">
                    <p className="weorweietdf">
                      Acesso Fácil ao Planner QRCode em capa página
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie nmsdfeur">
        <div className="container">
          <div className="row">
            <div className="col-md-5 snaekre">
              <div className="h23iasfwe2323">
                <p className="nasdfiwnf1">
                  Este <span>Programa</span>
                </p>
                <p className="nasdfiwnf">
                  de <span>Mentoria</span> é para
              </p>
                <p className="nasdfiwnf1"> VOCÊ QUE...</p>

              </div>
              <div className="asdfkhasiddeg">
                <img src="/images/oplaner.png" />
              </div>
            </div>
            <div className="col-md-7">
              <div>
                <div className="sandoasfjasuw12">
                  <p>
                    QUE NÃO SE SENTE NO CONTROLE. QUE PARECE QUE VIVE A VIDA
                    PARA OS OUTROS E MAL TE SOBRA TEMPO PRA CUIDAR DE VOCÊ.
                  </p>
                </div>
                <div className="sandoasfjasuw12">
                  <p>
                    QUE ESTÁ CANSADA DE ESCOLHER ENTRE A VIDA PESSOAL E O SEU
                    NEGÓCIO.
                  </p>
                </div>

                <div className="sandoasfjasuw12">
                  <p>
                    QUE SE SENTE FRUSTRADA POR NÃO CONSEGUIR DAR CONTA DE TUDO O
                    QUE É IMPORTANTE PRA VOCÊ.
                  </p>
                </div>

                <div className="sandoasfjasuw12">
                  <p>
                    QUE TENTA SER PRODUTIVA, QUE FAZ TANTO PARA TER QUASE NADA E
                    QUE NÃO SABE COMO FAZER DIFERENTE.
                  </p>
                </div>

                <div className="sandoasfjasuw12">
                  <p>
                    QUE QUER VIVER UMA VIDA PLENA SENDO MULHER, EMPRESÁRIA, MÃE,
                    ESPOSA E SER RECONHECIDA PROFISSIONALMENTE.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="isdfderf">
        <div className="container">
          <div className="zxnvuer d-flex">
            <div className="xjfudfsdi m-auto">
              <h1 className="skd-sdjfe">Eu</h1>
              <h2 className="skd-sdjfe">ACREDITO</h2>
              <h2 className="skd-sdjfe">Em VOCÊ</h2>
            </div>
            <div className="nsdjfrihf">
              <h1>Eu ACREDITO</h1>
              <p>
                Nas pessoas. Sei que elas podem mudar seus resultados se mudarem
                o jeito de pensar.
              </p>
              <p>
                Acredito que, a transformação de uma pessoa, pode significar
                relacionamentos mais bem sucedidos, filhos mais fortes e
                famílias mais unida.
              </p>
              <p>
                Acredito na reprogramação da mente baseada na ciência. E ela
                pode ser conquistada com pequenas ações diárias.
              </p>
              <p>
                Acredito que o mundo se torna um lugar melhor quando ajuda
                pessoas a transformarem suas vidas.
              </p>
              <p>
                Acredito em tudo isso, porque tive que por a prova todas essas
                crenças diante dos desafios que
              </p>
              <p>
                enfrentei ao longo da minha vida. Estar No Controle foi o que me
                garantiu o sucesso e o que tem garantido o sucesso de todos os
                que vivem essa experiência.
              </p>
              <h3>ELIS FERRAZ</h3>
            </div>
          </div>
          <div className="asjdiswjecsd">
            <div>
              <div>
                <h1 className="askdhasjwe-sdijw">

                  Um Jeito <span className="cksjdf">DIFERENTE</span> de
                  <span className="cksjdf sdkjeirfd">PENSAR</span>,
                </h1>
                <h1 className="askdhasjwe-sdijw">
                  <span className="cksjdf sdkjeirfd">ESTRUTURAR</span> e
                  <span className="cksjdf sdkjeirfd">Ganhar MAIS</span>
                </h1>
                <h1 className="askdhasjwe-sdijw">

                  na <span className="sdkjeirfd">VIDA</span> e nos
                  <span className="sdkjeirfd">NEGÓCIOS </span>
                </h1>
                <h1 className="askdhasjwe-sdijw">
                  Estando <span className="cksjdf sdkjeirfd">NO CONTROLE!</span>
                </h1>
              </div>
              <div className="mgt65">
                <p className="asjfiser">
                  Com 17 anos de experiência, tendo passado por mais de 280
                  empresas no Brasil e Estados Unidos, de diversos tamanho e
                  segmento. Ajudando mulheres e empresários a estarem No
                  Contorle da sua vida, da sua empresa e dos seus ganhos,
                  desenvolverem Alta Performance, tornando suas empresas Fonte
                  de Renda. Mostrando como desenvolver mentalidade estratégica
                  comercial para gerar maior conexão com clientes potenciais
                  transformando mais oportunidades em negócios. Elis Ferraz é
                  autora do High Performance Planner, único no mundo.
                  Desenvolveu vários programas de treinamento como 6 Super
                  Habilidades (implementado em multinacionais), 10em1 - 10 anos
                  de Faturamento em 1. É uma grande estudiosa e entusiasta nas
                  ciências da mente para mudança de mentalidade.
                </p>
              </div>
            </div>
            <div>
              <img className="ksdjiekfdf" src="/images/websd.png" />
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie pt-5 pb-4">
        <div className="container">
          <div className="xjbzeefb">
            <h1>NÓS ACREDITAMOS em Elis Ferraz!</h1>
            <div className="klgjt">
              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Rachel França</p>
                    <span>Empresária | Arquiteta</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “Aprender a atitude certa, desenvolvendo Alta Performance me
                  fez decolar na vida!”
                </p>
              </div>

              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Isis Leal</p>
                    <span>Empresária | Teatro</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “A mudança de Mentalidade é a chave para alavancar na vida e
                  nos negócios!”
                </p>
              </div>

              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Mel Domezi</p>
                    <span>Empresária</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “A transformação do meu jeito de pensar, me fez conquistar
                  muito, incluive fontes de renda!”
                </p>
              </div>
            </div>
            <div className="nsdairejrog1sd mt-5">
              <div className="xkdnidr11sds">
                <div>
                  <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                </div>
                <div className="d-flex align-items-center">
                  <div>
                    <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                    <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                  </div>
                  <img className="eruwherhd" src="/images/arwcrl.png" />
                  <div className="asdfiher-sdw ">
                    <p className="sdrehidf">EU QUERO</p>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="o2wqsasnw pt-4 pb-4">
        <div className="container">
          <div className="snafjrjifjg">
            <div className="row">
              <div className="col-md-6">
                <div>
                  <img className="nisetje" src="/images/fotoelis.png" />
                  <div className="jfaewisf">
                    <p className="agdhgegg">ELIS FERRAZ</p>
                    <div className="sdfgjiet"></div>
                  </div>
                </div>
              </div>
              <div className="col-md-6">
                <div className="czxbvdsuf">
                  <h1>Quem</h1>
                  <h6>será sua </h6>
                  <h2>MENTORA e</h2>
                  <h2>Treinadora ?</h2>
                </div>
              </div>
            </div>
            <div>
              <p className="dfjaier">
                Elis é empresária há mais de 17 anos. Passou por mais de 280
                empresas atuando em estratégias, gestão comercial, contratação,
                desenvolvimento de pessoas e de mentalidade de alta performance.
              </p>
            </div>

            <div className="gsdjhrgy">
              <h2>EMPRESÁRIA</h2>
              <div className="d-flex asfnsoirr3-23">
                <span>+</span>
                <h5> 17 anos de experiência</h5>
              </div>
            </div>
            <div className="gsdjhrgy asfosjr-seew">
              <h2>MENTORA E TREINADORA</h2>
              <div className="d-flex asfnsoirr3-23">
                <span>+</span>
                <h5> 2.000 pessoas Treinadas e mais de 280 empresas </h5>
              </div>
            </div>
            <div className="gsdjhrgy asfosjr-seew">
              <h2>Author</h2>
              <div className="m-0 d-flex asfnsoirr3-23">
                <span className="nsirefg">+</span>
                <h5>
                  15 programas de treinamentos, entre eles: 10em1 - 10 anos de
                  Faturamento em 1; 6 Super Habilidades - Influenciar | Escolher
                  | Escutar | Conversar | Negociar | Liderar; Programas de
                  Mentoria para empresas e empresários - No Controle | Alavancar
                  | Ganhar Mais.
                </h5>
              </div>
            </div>
          </div>
          <div className="cmdsfnief">
            <div>
              <img className="kndgofdg" src="/images/cloud.png" />
              <img className="sfdghidgr" src="/images/exam.png" />
            </div>
            <div className="ariothge">
              <div className="asfmsrh9wasf">
                <div className="znxiwebwwf">
                  <p className="sandsket">INSCREVER-ME AGORA NA MENTORIA</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bg-gry pt-4 pb-4">
        <div className="container">
          <div>
            <h1 className="ndsajfsdfer">ELIS Pra VOCÊ!</h1>
            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av2.jpg" />
                <img src="/images/port/av3.jpg" />
                <img src="/images/port/av4.jpg" />
                <img src="/images/port/av5.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo Minha História</p>
                </div>
              </div>
            </div>

            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av6.jpg" />
                <img src="/images/port/av7.jpg" />
                <img src="/images/port/av8.jpg" />
                <img src="/images/port/av9.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo Sou Mulher Série</p>
                </div>
              </div>
            </div>

            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av10.jpg" />
                <img src="/images/port/av11.jpg" />
                <img src="/images/port/av12.jpg" />
                <img src="/images/port/av13.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo No Controle Série</p>
                </div>
              </div>
            </div>
          </div>
          <div className="sdnserr i9ehdh283dcd">
            <img className="sadhee" src="/images/port/av1.png" />
            <div className="nsakdhe3 ihsa92wocns2">
              <h1 className="sceirjfg">EU, O PLANNER e uma Vida No CONTROLE</h1>



              <p>Você já pensou o que te faz realizar uma grande mudança?</p>
              <p>Para mim, foi estar entre a vida e a morte.</p>
              <p>
                Me tornei uma mulher bem sucedida, mas quando vieram os filhos e
                as responsabilidades com a família aumentaram, passei a ter que
                escolher entre ser empresária e ter uma família. Foram os anos
                mais difíceis de minha vida!
              </p>
              <p>
                O problema não era ter que conciliar a empresa e a família, era
                conciliar essas duas coisas que eu considerava uma prioridade
                tentando ser produtiva ao invés de estratégica sendo uma mulher
                de Alta Performance.
              </p>

              <p>
                Eu aprendi a estar No Controle da minha vida deixando de usar os
                modelos de produtividade criado para homens e por homens. Passei
                a adotar uma nova abordagem, fazendo as coisas do jeito mulher,
                aprendendo a colocar “Energia Certa no Lugar exato”. E dessa
                forma, acelerei meus resultados e passei a viver uma vida de
                muitas conquistas.
              </p>
              <p>A vida é um espelho que me reflete e eu gosto do que vejo!</p>
            </div>
          </div>



        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie pt-4 pb-4">
        <div className="container">
          <div className="sdanierhser">
            <h1 className="dsnierg">O MANIFESTO</h1>
            <div className="asdnfsdi"></div>

            <div className="nsdairejrog1sd mt-5">
              <div className="xkdnidr11sds">
                <div>
                  <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                </div>
                <div className="d-flex align-items-center">
                  <div>
                    <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                    <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                  </div>
                  <img className="eruwherhd" src="/images/arwcrl.png" />
                  <div className="asdfiher-sdw ">
                    <p className="sdrehidf">EU QUERO</p>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="sdafisrjenfd pt-4 pb-4">
        <div className="container">
          <div className="d-flex flex-wrap serhuisdfg justify-content-end">
            <img src="/images/brd/Copia de 1.png" />
            <img src="/images/brd/Copia de 2.png" />
            <img src="/images/brd/Copia de 3.png" />
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <img src="/images/brd/Copia de 4.png" />
            <img src="/images/brd/Copia de 5.png" />
            <img src="/images/brd/Copia de 6.png" />
            <img src="/images/brd/Copia de 7.png" />
            <img src="/images/brd/Copia de 8.png" />
            <img src="/images/brd/Copia de 9.png" />
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <img src="/images/brd/Copia de 10.png" />
            <img src="/images/brd/Copia de 11.png" />
            <img src="/images/brd/Copia de 12.png" />
            <img src="/images/brd/Copia de 13.png" />
            <img src="/images/brd/Copia de 14.png" />
            <img src="/images/brd/Copia de 15.png" />
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <img src="/images/brd/Copia de 16.png" />
            <img src="/images/brd/Copia de 17.png" />
            <img src="/images/brd/Copia de 18.png" />
            <img src="/images/brd/Copia de 19.png" />
            <img src="/images/brd/Copia de 20.png" />
            <img src="/images/brd/Copia de 21.png" />
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <img src="/images/brd/Copia de 21.png" />
            <img src="/images/brd/Copia de 22.png" />
            <img src="/images/brd/Copia de 23.png" />
            <img src="/images/brd/Copia de 24.png" />
            <img src="/images/brd/Copia de 25.png" />
            <img src="/images/brd/Copia de 26.png" />
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <img src="/images/brd/Copia de 27.png" />
            <img src="/images/brd/Copia de 28.png" />
            <img src="/images/brd/Copia de 29.png" />
            <img src="/images/brd/Copia de 30.png" />
            <img src="/images/brd/Copia de 31.png" />
            <img src="/images/brd/Copia de 32.png" />
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <Footer hasNav={true} />

    </div>
  );
}
