import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../src/components/navbar";
import Footer from "../src/components/footer";

export default function Home() {
  return (
    <div>
      <Nav />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="aslfjawe9irjeasi">
        <div className="container">
          <div className="d-flex justify-content-around align-items-center cont sheduewe2">
            <div className="sdfajiow39weiwxyz">
              <img src="/images/avts3.png" alt="img" />
            </div>
            <div className="">
              <div className="asdh83udashn3e">
                <div className="asd8quen9asdjmw">
                  <div className="asn9woewa092ojkasadkskd">
                    <h2 className="">MENTORIA</h2>
                  </div>
                </div>
                <div className="asn9woewa092ojkasadkskd">
                <h1 className="joasdfeioref">ALAVANCAR</h1>

                </div>
                <div className="asn9woewa092ojkasadkskd">
                <p className="sdfjeirere asdjalsd-sadjiw ">Você, No Controle da Sua Empresa!</p>

                </div>
                <div className="ascawuieda8ssdas9h3">
                  <img
                    className="sadasascawuieda8s9h3"
                    src="/images/sgn.png"
                    alt="img"
                  />
                </div>
              </div>
            </div>
            <div>
              <img src="/images/Alavancar.png" alt="img" />
            </div>
          </div>
          <div>
            <h5 className="sdeirjeoirf iojiwrwrjq1">
            Tornando sua empresa uma Fonte de Renda!
            </h5>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bg-gry pb-4">
        <div className="container pt-4">
          <div className="uaier934d asdhiferrsdf">
            <p>
            Diferente de um programa de mentoria para qualquer empresário... Este é o Programa de Mentoria Especializado para a Mulher Empresária ALAVANCAR sua empresa, se colocando No Controle para desenvolver pessoas e equipes autogerenciáveis para que seu negócio seja de Alta Performance, tornando Sua Empresa uma Fonte de Renda. Afinal de contas, você mulher, possui diferentes necessidades, prioridades e expectativas e, ao utilizar um modelo de gestão que potencializa o “Jeito Mulher” de fazer as coisas, você acelera seus resultados, possibilitando liberdade de tempo, dinheiro e estilo de vida como empresária.



           </p>

          </div>
          <div>
            <h4 className="asdnkdffd">

            Programa de Mentoria ALAVANCAR


</h4>
          </div>

          
          <div className="row">
            <div className="col-md-6">
              <div>

                <div className="asdhiferr">
                  <img className="ajissdsf-j8asdha" src="/images/notebook.png" />
                  <p className="masdkere">
                  Planner Exclusivo: 1 PLANNER enviado para sua casa.
EDIÇÃO LUXUOSA, ACABAMENTO PREMIUM, COLORIDO COM CAPA DURA.
                    </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf-j8asdha" src="/images/target1.png" />
                  <p className="masdkere">
                  Foco na Alta Performance da sua liderança na empresa. Desenvolvendo de Mentalidade Empresarial.

                    </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf-j8asdha" src="/images/dollar-coins.png" />
                  <p className="masdkere">
                  É o único Programa de Mentoria que apresenta uma estratégia de gestão prática e objetiva para transformar seu negócio em Fonte de Renda.  
 

                  </p>
                </div>
               
                <div className="asdhiferr">
                  <img className="ajissdsf-j8asdha" src="/images/businessman-success.png" />
                  <p className="masdkere">
                  Focando você nas ações vitais para acelerar resultados – Alta Performance para produtividade.

  
 
 
                  </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf-j8asdha" src="/images/rocket-with-speedometer-shape-on-it.png" />
                  <p className="masdkere">
                  Desenvolve em você habilidades para realizar a Revisão de Desempenho com as competências necessárias para preparar e educar as pessoas para se tornarem autogerenciáveis, dando a você o controle da sua empresa tornando uma fonte de renda.


  
 
                    </p>
                </div>

                <div className="asdhiferr">
                  <img className="ajissdsf-j8asdha" src="/images/badge.png" />
                  <p className="masdkere">
                  Método pratico de treinamento para manter a equipe comercial em um espiral de crescimento, atraindo com qualidade e convertendo em quantidade.
mente com mais velocidade – Hora de Ouro.



  
 

</p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf-j8asdha" src="/images/settings.png" />
                  <p className="masdkere">
                  Utiliza o High Performance PLANNER para liderar estando No Controle. Um Acelerador de Resultados para você desenvolver também nas pessoas novos hábitos, habilidades e crenças, promovendo mudança de mentalidade na equipe.


</p>
                </div>

              </div>
            </div>
            <div className="col-md-6">
              <div className="asdfidjer-sd"></div>



              






              <div className="nsdairejrog1sd mt-4">
                <div className="xkdnidr11">
                  <div>
                    <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                  </div>
                  <div className="d-flex align-items-center">
                    <div>
                      <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                      <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                    </div>
                    <img className="eruwherhd" src="/images/next.png" />
                    <div className="asdfiher-sdw sdfjdecdr">
                      <p className="sdrehidf">EU QUERO</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="o2wqsasnw pb-4">
        <div className="container">
       
          <div className="row">
            <div className="col-md-9">
              <div>
                <div className="asnasijweiasfbs-nau">
                  <img className="qjsdifef" src="/images/estrutura.png" />
                  <div className="iharnlsder">
                    <h4 className="asncoajew9osf"><span>VOCÊ,</span> finalmente,</h4>
                    <h4 className="asdi9jasf12f">
                      <span>No CONTROLE da</span>
                    </h4>
                    <h4 className="erudshfsdf">Sua Empresa!</h4>
                  </div>
                </div>
                <div className="oasow-cskds">
                  <div>
                    <p className="asfniajdwasw ihsdfww2032">
                      COMO FUNCIONA O PROGRAMA DE MENTORIA?
                    </p>
                    <p className="asfaojfsi3e ihsdfww20321">
                    Ao adquirir o Programa de Mentoria ALAVANCAR você...
                                        </p>
                  </div>
                  <div>
                    <div className="d-flex">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      Recebe 1 Planner na sua casa. <span className="ncasdkre">EDIÇÃO LUXUOSA ACABAMENTO PREMIUM, COLORIDO COM CAPA DURA.</span> O Hight Performance Planner será seu acelerador de resultados e vai te ajudar a desenvolver mentalidade estratégica empresarial.
 
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      Você vai aprender passo a passo como estar No Controle da sua empresa, desenvolvendo competências e habilidades específicas para fazer as pessoas fazerem o que tem que ser feito.  </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      Vai aprender como tornar as pessoas da sua equipe autogerenciáveis para que sua empresa seja uma empresa de alta performance
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      Vai tornar sua empresa fonte de renda por saber liderar sua equipe, contratar as pessoas certas, treinar, reduzir o tempo de aprendizado e tornar o propósito da empresa o propósito de seus colaboradores.  
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      Você será inserido no Grupo Exclusivo para ter acesso a conteúdos, ferramentas e testes para autoavaliação. 
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      Responderá a um questionário de alinhamento de expectativas e vai receber um link para participar das mentorias que são online, ao vivo e acontecem 1 vez por semana durante 3 meses -  90 dias, 2h por encontro.
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      Você pode e deve participar tirando dúvidas diretamente comigo, Elis Ferraz, durante as mentorias ou com a equipe de co-facilitadores..                      </p>
                    </div>
                  </div>
                </div>
                <div className="d-flex justify-content-end flex-column align-items-end">
                  <div className="ihasf937ds3h3">
                    <h5 className="asdniejsfwqe">
                      O MAIOR <span>BÔNUS</span>
                    </h5>
                    <h5 className="uhteahdg">da Sua Vida!</h5>
                    <img
                      className="asdf3jej0sawe"
                      src="/images/arrow-dwn.png"
                    />
                  </div>
                </div>
                <div className="d-flex naskerer">
                  <img className="asfh92jasdert-2131" src="/images/avt1.png" />
                  <div className="hriehudfdg">
                    <p className="asfniajdwasw">O PLANNER</p>
                   
                    <p className="nasidfasdnsfndsje">
                    É o primeiro Planner no mundo com esta proposta de Estilo de Vida de Alta Performance.  </p>
                    <p className="nasidfasdnsfndsje">
                    O High Performance Planner é um novo conceito e um novo estilo de vida de pessoas que querem estar No Controle. Foi desenvolvido para que, com menos esforço se tenha resultados extraordinários, promovendo Alta Performance e acelerando resultados.</p>
              
                    <p className="nasidfasdnsfndsje">
                    Um novo conceito baseado no que há de mais atual na ciência da mente que, através de ações simples, práticas e objetivas promove a mudança de mentalidade criando uma experiência única reprogramando sua mente para vencer. </p>
              
                  </div>
                </div>
                
              </div>
            </div>
            <div className="col-md-3">
              <div className="mt-5">
                <div className="ndskfiere">
                  <img src="/images/key.png" />
                  <div className="">
                    <p className="weorweietdf">
                    3 meses,12 mentorias, 
90 dias, 2h cada.
                    </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/face.png" />
                  <div className="">
                    <p className="weorweietdf">
                    Mentoria Ao Vivo e Interativa           </p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <div>
                    <img src="/images/cam.png" />
                    <img src="/images/mic.png" />
                  </div>

                  <div className="">
                    <p className="weorweietdf">Vídeo Aulas e PodCast</p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <img src="/images/booksm.png" />
                  <div className="">
                    <p className="weorweietdf">Ferramentas, PDFs e 
Testes de Comportamento</p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <img src="/images/chat.png" />
                  <div className="">
                    <p className="weorweietdf">
                    Equipe de Suporte e encontros comigo.               </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/lock.png" />
                  <div className="">
                    <p className="weorweietdf">
                    Grupo Exclusivo de Mentoria, atividade dupla. complementares                   </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/qr.png" />
                  <div className="">
                    <p className="weorweietdf">
                    Acesso Fácil ao Planner QRCode em capa página               </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie nmsdfeur">
        <div className="container">
          <div className="row">
            <div className="col-md-5 snaekre">
             <div className="h23iasfwe2323"> <p className="nasdfiwnf1">
                Este <span className="fto-dsf">Programa</span>
              </p>
              <p className="nasdfiwnf">
                de <span>Mentoria</span> é para
              </p>
              <p className="nasdfiwnf1"> VOCÊ QUE...</p>
             </div>
              <div className="asdfdsakhasiddeg">
                <img src="/images/book1.png" />
              </div>
            </div>
            <div className="col-md-7">
              <div>
                <div className="sandoasfjasuw12">
                  <p>
                  VOCÊ QUE TRABALHA MUITO, NÃO VÊ RESULTADOS E ESTÁ CANSADO DE TAMBÉM NÃO VER A EMPRESA CRESCER COMO DEVERIA.
                  </p>
                </div>
                <div className="sandoasfjasuw12">
                  <p>
                  VOCÊ QUE CARREGA SOZINHO A EMPRESA NAS COSTAS E QUER QUE SEUS FUNCIONÁRIOS FAÇAM O QUE TEM QUE SER FEITO.
                  </p>
                </div>

                <div className="sandoasfjasuw12">
                  <p>
                  VOCÊ QUE QUER QUE SUA EMPRESA SE TORNE UMA FONTE DE RENDA E NÃO MAIS UMA FONTE DE TRABALHO E DOR DE CABEÇA.
                  </p>
                </div>

                <div className="sandoasfjasuw12">
                  <p>
                  VOCÊ QUE SENTE QUE NÃO ESTÁ NO CONTROLE DA SUA EMPRESA E NEM MUITO MENOS DOS SEUS RESULTADOS.
                  </p>
                </div>

                <div className="sandoasfjasuw12">
                  <p>
                  VOCÊ QUE QUER TER UMA EMPRESA LUCRATIVA DE ALTA PERFORMANCE COM PESSOAS AUTOGERENCIÁVEIS, PARA QUE VOCÊ TENHA TEMPO E QUALIDADE DE VIDA.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="isdfderf">
        <div className="container">
          <div className="zxnvuer d-flex">
            <div className="xjfudfsdi iaotjedsjofsdf">
              <h1 className="skd-sdjfe">Eu</h1>
              <h2 className="skd-sdjfe">ACREDITO</h2>
              <h2 className="skd-sdjfe" style={{    fontSize: 56}}>Em VOCÊ</h2>
            </div>
            <div className="nsdjfrihf">
              <h1>Eu ACREDITO</h1>
              <p>
                Nas pessoas. Sei que elas podem mudar seus resultados se mudarem
                o jeito de pensar.
              </p>
              <p>
                Acredito que, a transformação de uma pessoa, pode significar
                relacionamentos mais bem sucedidos, filhos mais fortes e
                famílias mais unida.
              </p>
              <p>
                Acredito na reprogramação da mente baseada na ciência. E ela
                pode ser conquistada com pequenas ações diárias.
              </p>
              <p>
                Acredito que o mundo se torna um lugar melhor quando ajuda
                pessoas a transformarem suas vidas.
              </p>
              <p>
                Acredito em tudo isso, porque tive que por a prova todas essas
                crenças diante dos desafios que
              </p>
              <p>
                enfrentei ao longo da minha vida. Estar No Controle foi o que me
                garantiu o sucesso e o que tem garantido o sucesso de todos os
                que vivem essa experiência.
              </p>
              <h3>ELIS FERRAZ</h3>
            </div>
          </div>
          <div className="asjdiswjecsd">
            <div>
              <div>
                <h1 className="askdhasjwe-sdijw">

                  Um Jeito <span className="cksjdf">DIFERENTE</span> de
                  <span className="cksjdf sdkjeirfd"> PENSAR</span>,
                </h1>
                <h1 className="askdhasjwe-sdijw">
                  <span className="cksjdf sdkjeirfd">ESTRUTURAR</span> e
                  <span className="cksjdf sdkjeirfd"> Ganhar MAIS</span>
                </h1>
                <h1 className="askdhasjwe-sdijw">

                  na <span className="sdkjeirfd">VIDA</span> e nos
                  <span className="sdkjeirfd"> NEGÓCIOS </span>
                </h1>
                <h1 className="askdhasjwe-sdijw">
                  Estando <span className="cksjdf sdkjeirfd">NO CONTROLE!</span>
                </h1>
              </div>
              <div className="mgt65">
                <p className="asjfiser">
                Com 17 anos de experiência, tendo passado por mais de 280 empresas no Brasil e Estados Unidos, de diversos tamanho e segmento. Ajudando mulheres e empresários a estarem No Contorle da sua vida, da sua empresa e dos seus ganhos, desenvolverem Alta Performance, tornando suas empresas Fonte de Renda. Mostrando como desenvolver mentalidade estratégica comercial para gerar maior conexão com clientes potenciais transformando mais oportunidades em negócios.
                </p>
                <p className="asjfiser">
                Elis Ferraz é autora do High Performance Planner, único no mundo. Desenvolveu vários programas de treinamento como 6 Super Habilidades (implementado em multinacionais), 10em1 - 10 anos de Faturamento em 1. 
É uma grande estudiosa e entusiasta nas ciências da mente para mudança de mentalidade. </p>
              </div>
            </div>
            <div>
              <img className="ksdjiekfdf" src="/images/websd.png" />
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie pt-5 pb-4">
        <div className="container">
          <div className="xjbzeefb">
            <h1>NÓS ACREDITAMOS em Elis Ferraz!</h1>
            <div className="klgjt">
              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Rachel França</p>
                    <span>Empresária | Arquiteta</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “Aprender a atitude certa, desenvolvendo Alta Performance me
                  fez decolar na vida!”
                </p>
              </div>

              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Isis Leal</p>
                    <span>Empresária | Teatro</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “A mudança de Mentalidade é a chave para alavancar na vida e
                  nos negócios!”
                </p>
              </div>

              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Mel Domezi</p>
                    <span>Empresária</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “A transformação do meu jeito de pensar, me fez conquistar
                  muito, incluive fontes de renda!”
                </p>
              </div>
            </div>
            <div className="nsdairejrog1sd mt-5">
              <div className="xkdnidr11sds">
                <div>
                  <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                </div>
                <div className="d-flex align-items-center">
                  <div>
                    <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                    <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                  </div>
                  <img className="eruwherhd" src="/images/arwcrl.png" />
                  <div className="asdfiher-sdw ">
                    <p className="sdrehidf">EU QUERO</p>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="o2wqsasnw pt-4 pb-4">
        <div className="container">
          <div className="snafjrjifjg">
            <div className="row ojsdakwqpd">
              <div className="col-md-6">
                <div>
                  <img className="nisetje" src="/images/fotoelis.png" />
                  <div className="jfaewisf">
                    <p className="agdhgegg">ELIS FERRAZ</p>
                    <div className="sdfgjiet"></div>
                  </div>
                </div>
              </div>
              <div className="col-md-6">
                <div className="czxbvdsuf">
                  <h1>Quem</h1>
                  <h6>será sua </h6>
                  <h2>MENTORA e</h2>
                  <h2>Treinadora ?</h2>
                </div>
              </div>
            </div>
            <div>
              <p className="dfjaier">
                Elis é empresária há mais de 17 anos. Passou por mais de 280
                empresas atuando em estratégias, gestão comercial, contratação,
                desenvolvimento de pessoas e de mentalidade de alta performance.
              </p>
            </div>

            <div className="gsdjhrgy">
              <h2>EMPRESÁRIA</h2>
              <div className="d-flex asfnsoirr3-23">
                <span>+</span>
                <h5> 17 anos de experiência</h5>
              </div>
            </div>
            <div className="gsdjhrgy asfosjr-seew">
              <h2>MENTORA E TREINADORA</h2>
              <div className="d-flex asfnsoirr3-23">
                <span>+</span>
                <h5> 2.000 pessoas Treinadas e mais de 280 empresas </h5>
              </div>
            </div>
            <div className="gsdjhrgy asfosjr-seew">
              <h2>Author</h2>
              <div className="m-0 d-flex asfnsoirr3-23">
                <span className="nsirefg">+</span>
                <h5>
                  15 programas de treinamentos, entre eles: 10em1 - 10 anos de
                  Faturamento em 1; 6 Super Habilidades - Influenciar | Escolher
                  | Escutar | Conversar | Negociar | Liderar; Programas de
                  Mentoria para empresas e empresários - No Controle | Alavancar
                  | Ganhar Mais.
                </h5>
              </div>
            </div>
          </div>
          <div className="cmdsfnief">
            <div>
              <img className="kndgofdg" src="/images/cloud.png" />
              <img className="sfdghidgr" src="/images/exam.png" />
            </div>
            <div className="ariothge">
              <div className="asfmsrh9wasf">
                <div className="znxiwebwwf">
                  <p className="sandsket">INSCREVER-ME AGORA NA MENTORIA</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bg-gry-1s pt-4 pb-4">
        <div className="container">
          <div>
            <h1 className="ndsajfsdfer">ELIS Pra VOCÊ!</h1>
            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av2.jpg" />
                <img src="/images/port/av3.jpg" />
                <img src="/images/port/av4.jpg" />
                <img src="/images/port/av5.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo Minha História</p>
                </div>
              </div>
            </div>

            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av6.jpg" />
                <img src="/images/port/av7.jpg" />
                <img src="/images/port/av8.jpg" />
                <img src="/images/port/av9.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo Sou Mulher Série</p>
                </div>
              </div>
            </div>

            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av10.jpg" />
                <img src="/images/port/av11.jpg" />
                <img src="/images/port/av12.jpg" />
                <img src="/images/port/av13.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo No Controle Série</p>
                </div>
              </div>
            </div>
          </div>

          <div className="sdnserr">
            <img className="sadhee hiodsgsdodg" src="/images/port/av1.png" />
            <div className="nsakdhe3">
              <h1 className="sceirjfg">EU e Minha Empresa No CONTROLE</h1>

              <p>
              Depois de passar por mais de 280 empresas nesses quase 18 anos de experiência, presenciei, assistindo de camarote o espetáculo ao vivo de ver empresas com resultados incríveis e aquelas que mal sobreviviam.
              </p>
        
              <p>
              Eu era contratada para dobrar e triplicar os ganhos dessas empresas. E, porque que quando eu terminava meu trabalho, alguns meses depois elas me chamavam novamente para refazer o trabalho em quando uma minoria seguia em frente?      
              </p>
              <p>
              Por incrível que pareça, o problema estava sob 4 perspectivas diferentes: a visão do empresário em relação ao negócio, a clareza e alinhamento de expectativa de cada setor, a duplicação dos valores, propósito e visão do negócio pelas pessoas que estavam diretamente ligadas ao empresário e a execução por parte dos colaboradores.
              </p>
              <br></br>
              <p>E, quando a liderança dessa empresa estava sob o comando de uma mulher empresária, duas coisas aconteciam... Ou ela fazia o negócio dar certo abrindo mão da sua vida ou ela tentava conciliar a vida com o negócio e as coisas não iam muito bem.</p>
              <p>O problema não era conciliar as duas coisas importantes para ela, era não saber fazer de uma maneira diferente, não saber como estar No Controle fazendo do “Jeito Mulher” usando suas habilidades únicas e seu maior poder que são as emoções, que faz com que ela se conecte as pessoas e tenha maior capacidade de liderança.</p>
              <br></br>
              <p>Mulher Empresária, eu já cometi o grande erro de tentar fazer as coisas usando modelos de gestão e produtividade criado para homens, por homens em um mundo dos negócios criado para eles. E quero prestar aqui, meu solene testemunho, como prova viva, por ter acompanhado de perto tantos empresários homens que, os mais bem sucedidos entre eles, eram os que buscavam desenvolver essa capacidade de se conectar através das emoções. Enquanto tentamos seguir o padrão masculino, os homens de sucesso tentam encontrar o jeito feminino de fazer as coisas. </p>
              <br></br>
              <p>Pense nisso! Você sabe que foi ensinada a ser qualquer coisa, menos uma mulher empresária, bem sucedida e reconhecida. A vida pode ser diferente se você agir diferente!</p>
           </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie pt-4 pb-4">
        <div className="container">
          <div className="sdanierhser">
            <h1 className="dsnierg">O MANIFESTO</h1>
            <div className="asdnfsdi"></div>

            <div className="nsdairejrog1sd mt-5">
              <div className="xkdnidr11sds">
                <div>
                  <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                </div>
                <div className="d-flex align-items-center">
                  <div>
                    <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                    <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                  </div>
                  <img className="eruwherhd" src="/images/arwcrl.png" />
                  <div className="asdfiher-sdw ">
                    <p className="sdrehidf">EU QUERO</p>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>
      <section className="sdafisrjenfd pt-4 pb-4">
        <div className="container">
        <div className="d-flex flex-wrap serhuisdfg justify-content-end">
          <img src="/images/brd/Copia de 1.png"/>
          <img src="/images/brd/Copia de 2.png"/>
          <img src="/images/brd/Copia de 3.png"/>
          
        </div>
        <div className="d-flex flex-wrap justify-content-center">
          <img src="/images/brd/Copia de 4.png"/>
          <img src="/images/brd/Copia de 5.png"/>
          <img src="/images/brd/Copia de 6.png"/>
          <img src="/images/brd/Copia de 7.png"/>
          <img src="/images/brd/Copia de 8.png"/>
          <img src="/images/brd/Copia de 9.png"/>
        </div>
        <div className="d-flex flex-wrap justify-content-center">
          <img src="/images/brd/Copia de 10.png"/>
          <img src="/images/brd/Copia de 11.png"/>
          <img src="/images/brd/Copia de 12.png"/>
          <img src="/images/brd/Copia de 13.png"/>
          <img src="/images/brd/Copia de 14.png"/>
          <img src="/images/brd/Copia de 15.png"/>
        </div>
        <div className="d-flex flex-wrap justify-content-center">
          <img src="/images/brd/Copia de 16.png"/>
          <img src="/images/brd/Copia de 17.png"/>
          <img src="/images/brd/Copia de 18.png"/>
          <img src="/images/brd/Copia de 19.png"/>
          <img src="/images/brd/Copia de 20.png"/>
          <img src="/images/brd/Copia de 21.png"/>
        </div>
        <div className="d-flex flex-wrap justify-content-center">
          <img src="/images/brd/Copia de 21.png"/>
          <img src="/images/brd/Copia de 22.png"/>
          <img src="/images/brd/Copia de 23.png"/>
          <img src="/images/brd/Copia de 24.png"/>
          <img src="/images/brd/Copia de 25.png"/>
          <img src="/images/brd/Copia de 26.png"/>
        </div>
        <div className="d-flex flex-wrap justify-content-center">
          <img src="/images/brd/Copia de 27.png"/>
          <img src="/images/brd/Copia de 28.png"/>
          <img src="/images/brd/Copia de 29.png"/>
          <img src="/images/brd/Copia de 30.png"/>
          <img src="/images/brd/Copia de 31.png"/>
          <img src="/images/brd/Copia de 32.png"/>
        </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <Footer hasNav={true}/>

      </div>
  );
}
