import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../src/components/navbar";
import Footer from "../src/components/footer";

export default function Home() {
    return (
        <div>
            <Nav />
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className="bf-josdafer">
                <div className="container pb-100">
                    <div className="nvisd0-0rwez1">
                        <h1>Quer Falar Comigo?</h1>
                        <h2>OK, Vamos Conversar. Como Prefere?</h2>
                    </div>
                    <div className="bg-contact ndosapfs-ewsffe">
                        <div className="w-50p">
                            <div className="ndsfd-wead23113">
                                <div className="ndsfd-wead23113-123">
                                    <h5 className="ndvsias-fsde3">Me manda um Whatsapp</h5>
                                    <div className="isdfds-e2asdsd">
                                        <img className="img-sfecx23" src="/images/i0.png" />
                                        <h2 className="hsd0e-ad223as2">+ 55 11 94981-5924</h2>
                                    </div>
                                    <h5 className="ndvsias-fsde3">Me encontre nas Redes Sociais</h5>
                                    <div className="isdfds-e2asdsd-1">
                                        <img src="/images/i1.png" className="dsifj-21nsa234" />
                                        <h3 className="nisdafew-wewds">@elisferraz_</h3>
                                    </div>
                                    <div className="isdfds-e2asdsd-1">
                                        <img src="/images/i2.png" className="dsifj-21nsa234" />
                                        <h3 className="nisdafew-wewds">Elis Ferraz Oficial</h3>
                                    </div>
                                    <div className="isdfds-e2asdsd-1">
                                        <img src="/images/i6.png" className="dsifj-21nsa234" />
                                        <h3 className="nisdafew-wewds">No Controle</h3>
                                    </div>
                                    <div className="isdfds-e2asdsd-1">
                                        <img src="/images/i5.png" className="dsifj-21nsa234" />
                                        <h3 className="nisdafew-wewds">elisferraz</h3>
                                    </div>
                                    <div className="isdfds-e2asdsd-1">
                                        <img src="/images/i4.png" className="dsifj-21nsa234" />
                                        <h3 className="nisdafew-wewds">elis-ferraz</h3>
                                    </div>
                                    <div className="isdfds-e2asdsd-1">
                                        <img src="/images/i3.png" className="dsifj-21nsa234" />
                                        <h3 className="nisdafew-wewds">Elis Ferraz Oficial</h3>
                                    </div>
                                    <div className="isdfds-e2asdsd-1">
                                        <img src="/images/i7.png" className="dsifj-21nsa234" />
                                        <h3 className="nisdafew-wewds">@elisferraz</h3>
                                    </div>
                                    <h5 className="ndvsias-fsde3">Equipe Fator de Sucesso</h5>
                                    <h4 className="ndvsias-fsde3-1">11 98228-0233 | 11 98202-2002</h4>
                                </div>
                            </div>
                        </div>

                        <div className="w-50p">
                            <div className="ndsfd-wead23113">
                                <div className="ndsfd-wead23113-123-1">
                                    <h5 className="ndvsias-fsde3-2">Me manda uma Mensagem</h5>
                                   <div className="djsa-fsda3easf12cz">
                                   <input placeholder="Nome" className="jdksfj-asdew" />
                                    <input placeholder="Whatsapp" className="jdksfj-asdew"/>
                                    <input placeholder="Seu Melhor e-Mail" className="jdksfj-asdew"/>
                                    <textarea rows={8} placeholder="Mensagem..." className="iasfjdo-12ejc23"></textarea>
                                   <div className="snai-sajdawie">
                                       <button className="btn">ENVIAR</button>
                                   </div>
                                   <div className="idsjf-asewhsf">
                                       <img className="nkdsfd-29cjad" src="/images/egl.png"/>
                                       <img className="nkdsfd-29cjad-1" src="/images/sgn.png"/>
                                   </div>
                                   </div>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </section>
            <div className="niokfiecnn2"></div>
            <section className="bg-mkt">
            <div className="container nidsha-e39uadr3">
                <div className="asdojfs-aswusa">
                    <div className="mt-3"><h5>Vai ser muito bom</h5>
                    <h5>falar com você!</h5></div>
                    <div className="mt-5"><h5>Aguardo seu contato.</h5></div>
                    <div className="mt-5 mb-3"><h5>Elis Ferraz</h5></div>
                </div>
            </div>
            </section>
            <div className="niokfiecnn2"></div>

            <Footer hasNav={true} />
        </div>
    );
}
