import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../src/components/navbar";
import Footer from "../src/components/footer";

export default function Home() {
  return (
    <div>
      <Nav />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="aslfjawe9irjeasi">
        <div className="container">
          <div className="d-flex justify-content-around align-items-center cont sheduewe2">
            <div className="sdfajiow39weiw">
              <img src="/images/avts2.png" alt="img" />
            </div>
            <div className="">
              <div className="asdh83udashn3e">
                <div className="asd8quen9asdjmw">
                  <div className="asn9woewa092ojkasadkskd">
                    <h2 className="skdfneefecs jiasdisdfw">MENTORIA</h2>
                  </div>
                </div>
                <h1 className="oojqwhq-uduasd">GANHAR MAIS</h1>
                <p className="sdfjeirere-21712 asdjalsd-sadjiw niasnfsfsdf">Você, No Controle da Sua VIDA!</p>
                <p className="sdfjeirere-21712 asdjalsd-sadjiw niasnfsfsdf">Ganhos e Resultados!</p>
                <div className="ascawuieda8ssdas9h3">
                  <img
                    className="sadasascawuieda8s9h3"
                    src="/images/sgn.png"
                    alt="img"
                  />
                </div>
              </div>
            </div>
            <div>
              <img src="/images/Bhj.png" alt="img" />
            </div>
          </div>
          <div>
            <h5 className="sdeirjeoirf">
              Ter Mentalidade Estratégica Comercial é o Segredo das Empresas que Ganham Mais!
            </h5>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bg-gry pb-4">
        <div className="container pt-4">
          <div className="uaier934d asdhiferrsdf">
            <p>
              Quando o assunto é fazer dinheiro, é impossível não imaginar uma estratégia comercial bem elaborada por trás de tudo!
            </p>
            <p> Não estou dizendo que você deve ser a área comercial da sua empresa. O que estou dizendo é que a única maneira de estar no controle dos ganhos e resultados e tendo esta mentalidade estratégica comercial desenvolvida para criar oportunidades transformando em negócios fechados se conectando com pessoas.  </p>
            <p>E foi pensando nisto que criamos o único Programa de Mentoria com Foco no Desenvolvimento de Mentalidade Estratégica Comercial. Com o objetivo de posicionar a mulher empresária no controle dos ganhos e resultados com inteligência comercial para gerar conexão, dominando comercialmente o seu negócio: funis de venda, gerar impacto emocional com storytelling e maior engajamento dos clientes, determinando o posicionamento do seu negócio on-line | off-line, elaborando estratégias para as esteiras de venda e treinamento da equipe para Atrair com Qualidade e Converter em Quantidade.</p>

          </div>
          <div>
            <h4 className="asdnkdffd">
              Programa de Mentoria GANHAR MAIS
                  </h4>
          </div>

          <div className="asdhiferr ojasodase iioasrnewir">
            <img className="ajissdsf" src="/images/interview.png" />
            <p className="masdkere ">
              <span>
                Você RECEBERÁ
                  </span> Entrevista de Alinhamento de Expectativa com Elis Ferraz para definir seus objetivos de ganhos e resultados
                  </p>
          </div>
          <div className="row">
            <div className="col-md-6">
              <div>

                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/strategy.png" />
                  <p className="masdkere">
                    <span>Foco em Alta Performance Comercial,</span> Desenvolvendo <span>Mentalidade Estratégica</span> para estar No Controle dos Ganhos e Resultados aprendendo a desenvolver estratégias objetivas e práticas estando No Controle dos resultados..
                  </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/abducted-man.png" />
                  <p className="masdkere">
                    É <span>o único Programa de Mentoria</span> que apresenta uma estratégia de liderança comercial objetiva e prática te mostrando como gerar oportunidades, se conectar com pessoas e diferentes níveis.
                  </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/funnel.png" />
                  <p className="masdkere">
                    <span>Posicionamento da sua empresa online e off-line</span> com uma comunicação clara e específica para gerar conexão com seu público gerando maiores oportunidades de negócio.



                  </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/chronometer.png" />
                  <p className="masdkere">
                    <span>Estruturação da área comercial:</span> Objetivos de performance, metas, funis de venda, treinamentos para se manterem em um espiral de crescimento.
                  </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/payment-method.png" />
                  <p className="masdkere">
                    <span>Método SPEED</span> de treinamento que reduz em 80% o tempo de aprendizado e potencializa em mais de 300% o desempenho comercial.
qualidade e convertendo em quantidade.
mente com mais velocidade – Hora de Ouro.

                  </p>
                </div>
                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/conversation.png" />
                  <p className="masdkere">
                    <span>Método de vendas </span> (técnicas e estratégias) para <span>Atrair com Qualidade e Converter em Quantidade.</span>
                  </p>
                </div>

                <div className="asdhiferr">
                  <img className="ajissdsf" src="/images/salute-of-hand-of-different-human-races-of-the-world.png" />
                  <p className="masdkere">
                    <span>
                      Diferenciais competitivos:
                   </span> Herança, Autenticidade e Compromisso com a Qualidade.


</p>
                </div>

              </div>
            </div>
            <div className="col-md-6">
              <div className="asdfidjer-sd"></div>



              <div className="asdhiferr mt-4">
                <img className="ajissdsf" src="/images/hand-cash-circular-symbol.png" />
                <p className="masdkere nsdjfier">
                  As mentorias são <span>Ao Vivo</span> e Totalmente <span>Interativas: 3h por semana,</span> durante 90 dias, <span>3 meses</span> com <span>Conteúdos e Atividades</span> em todos os encontros.
Atividades Semanais:  <span>Ferramentas</span> para aplicar no seu negócio e <span>PodCast Exclusivo.</span> Acessos:  <span>Grupo Fechado</span> de Mentoria.



</p>
              </div>






              <div className="nsdairejrog1sd mt-4">
                <div className="ioja9secsjse xkdnidr11">
                  <div>
                    <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                  </div>
                  <div className="d-flex align-items-center">
                    <div>
                      <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                      <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                    </div>
                    <img className="eruwherhd" src="/images/next.png" />
                    <div className="asdfiher-sdw sdfjdecdr">
                      <p className="sdrehidf">EU QUERO</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="o2wqsasnw pt-4 pb-4">
        <div className="container">
        <div className="asnasijweiasfbs-nau-1">
                  <img className="qjsdifef9us3123d" src="/images/vendas.png" />
                  <div>
                    <h4 className="asncoajew9osf">VOCÊ, finalmente,</h4>
                    <h4 className="asdi9jasf12f lniar8n2823">
                      <span>No CONTROLE dos</span>
                    </h4>
                    <h4 className="erudshfsdf lniar8n28231">Seus <span style={{fontWeight:'600'}}>Ganhos</span> e</h4>
                    <h4 className="erudshfsdf lniar8n28232" style={{fontWeight:'600'}}>Resultados!</h4>
                  </div>
                </div>
                
          <div className="row">
            <div className="col-md-9 pt-5 ajiwmaskf">
              <div>
               <div className="ja9swejsaqw">
                  <div>
                    <p className="asfniajdwasw ihsdfww2032">
                      COMO FUNCIONA O PROGRAMA DE MENTORIA?
                    </p>
                    <p className="asfaojfsi3e ihsdfww20321">
                    Ao adquirir o Programa de Mentoria GANHAR MAIS você...
                    </p>
                  </div>
                  <div >
                    <div className="d-flex">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      Faz uma ENTREVISTA EXCLUSIVA DE ALINHAMENTO de expectativa com Elis Ferraz para identificar seus objetivos de ganhos e resultados.                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      Todo o programa é voltado para Alta Performance na Área Comercial, portanto terá foco em estrastégias para “Atrair com Qualidade e Converter em Quantidade” - Conexão voltada a conversão de oportunidades em negócios.
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      VAI RECEBER acesso a todas as áreas para baixar ferramentas que utilizará durante as mentorias.
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      RECEBERÁ ATIVIDADES e um conteúdo de STORYTELLING em PDF antes do início das mentorias como forma de preparação para o programa. 
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      Será preparado para Desenvolver Mentalidade Estartégica Comercial com Metodologia desenvolvida para empresários - Prática e Objetiva.
                      </p>
                  
                    
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                        <p className="asfaojfsi3e osif9eu-we9e">
                      Poderá convidar um par que vai atuar junto com você na área comercial para participar do programa e realizar a implementação.    </p>
                    
                     
                    
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                    <p className="asfaojfsi3e osif9eu-we9e">
                      Você será inserido no Grupo Exclusivo para ter acesso a conteúdos, ferramentas e testes para autoavaliação e avaliação da equipe. 
 </p>
                 
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                      Receber  link para participar das mentorias que são online, ao vivo e que acontecem 1 ou 2 vezes por semana completando 3h semanais durante 3 meses -  90 dias.  
             </p>
                      
                 
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
<p className="asfaojfsi3e osif9eu-we9e">
                      Você pode e deve participar tirando dúvidas diretamente comigo, Elis Ferraz, durante as mentorias ou com a equipe de co-facilitadores..
                    </p>  
                 
                    </div>
                  </div>
                </div>

               </div>
            </div>
            <div className="col-md-3">
              <div className="mt-5">
                <div className="ndskfiere">
                  <img src="/images/key.png" />
                  <div className="">
                    <p className="weorweietdf">
                      3 meses,12 mentorias, 90 dias, 90 minutos cada.
                    </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/face.png" />
                  <div className="">
                    <p className="weorweietdf">Mentoria Ao Vivo e Interativa</p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <div>
                    <img src="/images/cam.png" />
                    <img src="/images/mic.png" />
                  </div>

                  <div className="">
                    <p className="weorweietdf">Vídeo Aulas e PodCast</p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <img src="/images/booksm.png" />
                  <div className="">
                    <p className="weorweietdf">
                      Testes de Comportamento, PDFs e Ferramentas
                    </p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <img src="/images/chat.png" />
                  <div className="">
                    <p className="weorweietdf">
                      Equipe de Suporte e encontros comigo.
                    </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/lock.png" />
                  <div className="">
                    <p className="weorweietdf">
                      Grupo Exclusivo de Mentoria, atividade dupla.
                      complementares
                    </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/qr.png" />
                  <div className="">
                    <p className="weorweietdf">
                      Acesso Fácil ao Planner QRCode em capa página
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie nmsdfeur">
        <div className="container">
          <div className="row">
            <div className="col-md-5 snaekre">
              <div className="h23iasfwe2323">
              <p className="nasdfiwnf1">
                Este <span>Programa</span>
              </p>
              <p className="nasdfiwnf">
                de <span>Mentoria</span> é para
              </p>
              <p className="nasdfiwnf1"> VOCÊ QUE...</p>
           
              </div>
              <div className="asdfkhasiddeg">
                <img className="jaiodfie9r23" src="/images/fotoelis.png" />
              </div>
            </div>
            <div className="col-md-7">
              <div>
                <div className="sandoasfjasuw12">
                  <p>
                    QUE NÃO SE SENTE NO CONTROLE. QUE PARECE QUE VIVE A VIDA
                    PARA OS OUTROS E MAL TE SOBRA TEMPO PRA CUIDAR DE VOCÊ.
                  </p>
                </div>
                <div className="sandoasfjasuw12">
                  <p>
                    QUE ESTÁ CANSADA DE ESCOLHER ENTRE A VIDA PESSOAL E O SEU
                    NEGÓCIO.
                  </p>
                </div>

                <div className="sandoasfjasuw12">
                  <p>
                    QUE SE SENTE FRUSTRADA POR NÃO CONSEGUIR DAR CONTA DE TUDO O
                    QUE É IMPORTANTE PRA VOCÊ.
                  </p>
                </div>

                <div className="sandoasfjasuw12">
                  <p>
                    QUE TENTA SER PRODUTIVA, QUE FAZ TANTO PARA TER QUASE NADA E
                    QUE NÃO SABE COMO FAZER DIFERENTE.
                  </p>
                </div>

                <div className="sandoasfjasuw12">
                  <p>
                    QUE QUER VIVER UMA VIDA PLENA SENDO MULHER, EMPRESÁRIA, MÃE,
                    ESPOSA E SER RECONHECIDA PROFISSIONALMENTE.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="isdfderf">
        <div className="container">
          <div className="zxnvuer d-flex">
            <div className="xjfudfsdi m-auto">
              <h1 className="skd-sdjfe">Eu</h1>
              <h2 className="skd-sdjfe">ACREDITO</h2>
              <h2 className="skd-sdjfe">Em VOCÊ</h2>
            </div>
            <div className="nsdjfrihf">
              <h1>Eu ACREDITO</h1>
              <p>
                Nas pessoas. Sei que elas podem mudar seus resultados se mudarem
                o jeito de pensar.
              </p>
              <p>
                Acredito que, a transformação de uma pessoa, pode significar
                relacionamentos mais bem sucedidos, filhos mais fortes e
                famílias mais unida.
              </p>
              <p>
                Acredito na reprogramação da mente baseada na ciência. E ela
                pode ser conquistada com pequenas ações diárias.
              </p>
              <p>
                Acredito que o mundo se torna um lugar melhor quando ajuda
                pessoas a transformarem suas vidas.
              </p>
              <p>
                Acredito em tudo isso, porque tive que por a prova todas essas
                crenças diante dos desafios que
              </p>
              <p>
                enfrentei ao longo da minha vida. Estar No Controle foi o que me
                garantiu o sucesso e o que tem garantido o sucesso de todos os
                que vivem essa experiência.
              </p>
              <h3>ELIS FERRAZ</h3>
            </div>
          </div>
          <div className="asjdiswjecsd">
            <div>
              <div>
                <h1 className="askdhasjwe-sdijw">

                  Um Jeito <span className="cksjdf">DIFERENTE</span> de
                  <span className="cksjdf sdkjeirfd">PENSAR</span>,
                </h1>
                <h1 className="askdhasjwe-sdijw">
                  <span className="cksjdf sdkjeirfd">ESTRUTURAR</span> e
                  <span className="cksjdf sdkjeirfd">Ganhar MAIS</span>
                </h1>
                <h1 className="askdhasjwe-sdijw">

                  na <span className="sdkjeirfd">VIDA</span> e nos
                  <span className="sdkjeirfd">NEGÓCIOS </span>
                </h1>
                <h1 className="askdhasjwe-sdijw">
                  Estando <span className="cksjdf sdkjeirfd">NO CONTROLE!</span>
                </h1>
              </div>
              <div className="mgt65">
                <p className="asjfiser">
                  Com 17 anos de experiência, tendo passado por mais de 280
                  empresas no Brasil e Estados Unidos, de diversos tamanho e
                  segmento. Ajudando mulheres e empresários a estarem No
                  Contorle da sua vida, da sua empresa e dos seus ganhos,
                  desenvolverem Alta Performance, tornando suas empresas Fonte
                  de Renda. Mostrando como desenvolver mentalidade estratégica
                  comercial para gerar maior conexão com clientes potenciais
                  transformando mais oportunidades em negócios. Elis Ferraz é
                  autora do High Performance Planner, único no mundo.
                  Desenvolveu vários programas de treinamento como 6 Super
                  Habilidades (implementado em multinacionais), 10em1 - 10 anos
                  de Faturamento em 1. É uma grande estudiosa e entusiasta nas
                  ciências da mente para mudança de mentalidade.
                </p>
              </div>
            </div>
            <div>
              <img className="ksdjiekfdf" src="/images/websd.png" />
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie pt-5 pb-4">
        <div className="container">
          <div className="xjbzeefb">
            <h1>NÓS ACREDITAMOS em Elis Ferraz!</h1>
            <div className="klgjt">
              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Rachel França</p>
                    <span>Empresária | Arquiteta</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “Aprender a atitude certa, desenvolvendo Alta Performance me
                  fez decolar na vida!”
                </p>
              </div>

              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Isis Leal</p>
                    <span>Empresária | Teatro</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “A mudança de Mentalidade é a chave para alavancar na vida e
                  nos negócios!”
                </p>
              </div>

              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Mel Domezi</p>
                    <span>Empresária</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “A transformação do meu jeito de pensar, me fez conquistar
                  muito, incluive fontes de renda!”
                </p>
              </div>
            </div>
            <div className="nsdairejrog1sd mt-5">
              <div className="xkdnidr11sds">
                <div>
                  <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                </div>
                <div className="d-flex align-items-center">
                  <div>
                    <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                    <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                  </div>
                  <img className="eruwherhd" src="/images/arwcrl.png" />
                  <div className="asdfiher-sdw ">
                    <p className="sdrehidf">EU QUERO</p>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="o2wqsasnw pt-4 pb-4">
        <div className="container">
          <div className="snafjrjifjg">
            <div className="row">
              <div className="col-md-6">
                <div>
                  <img className="nisetje" src="/images/fotoelis.png" />
                  <div className="jfaewisf">
                    <p className="agdhgegg">ELIS FERRAZ</p>
                    <div className="sdfgjiet"></div>
                  </div>
                </div>
              </div>
              <div className="col-md-6">
                <div className="czxbvdsuf">
                  <h1>Quem</h1>
                  <h6>será sua </h6>
                  <h2>MENTORA e</h2>
                  <h2>Treinadora ?</h2>
                </div>
              </div>
            </div>
            <div>
              <p className="dfjaier">
                Elis é empresária há mais de 17 anos. Passou por mais de 280
                empresas atuando em estratégias, gestão comercial, contratação,
                desenvolvimento de pessoas e de mentalidade de alta performance.
              </p>
            </div>

            <div className="gsdjhrgy">
              <h2>EMPRESÁRIA</h2>
              <div className="d-flex asfnsoirr3-23">
                <span>+</span>
                <h5> 17 anos de experiência</h5>
              </div>
            </div>
            <div className="gsdjhrgy asfosjr-seew">
              <h2>MENTORA E TREINADORA</h2>
              <div className="d-flex asfnsoirr3-23">
                <span>+</span>
                <h5> 2.000 pessoas Treinadas e mais de 280 empresas </h5>
              </div>
            </div>
            <div className="gsdjhrgy asfosjr-seew">
              <h2>Author</h2>
              <div className="m-0 d-flex asfnsoirr3-23">
                <span className="nsirefg">+</span>
                <h5>
                  15 programas de treinamentos, entre eles: 10em1 - 10 anos de
                  Faturamento em 1; 6 Super Habilidades - Influenciar | Escolher
                  | Escutar | Conversar | Negociar | Liderar; Programas de
                  Mentoria para empresas e empresários - No Controle | Alavancar
                  | Ganhar Mais.
                </h5>
              </div>
            </div>
          </div>
          <div className="cmdsfnief">
            <div>
              <img className="kndgofdg" src="/images/cloud.png" />
              <img className="sfdghidgr" src="/images/exam.png" />
            </div>
            <div className="ariothge">
              <div className="asfmsrh9wasf">
                <div className="znxiwebwwf">
                  <p className="sandsket">INSCREVER-ME NA SEMANA DE MENTORIA</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="bg-gry-1s pt-4 pb-4">
        <div className="container">
          <div>
            <h1 className="ndsajfsdfer">ELIS Pra VOCÊ!</h1>
            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av2.jpg" />
                <img src="/images/port/av3.jpg" />
                <img src="/images/port/av4.jpg" />
                <img src="/images/port/av5.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo Minha História</p>
                </div>
              </div>
            </div>

            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av6.jpg" />
                <img src="/images/port/av7.jpg" />
                <img src="/images/port/av8.jpg" />
                <img src="/images/port/av9.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo Sou Mulher Série</p>
                </div>
              </div>
            </div>

            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av10.jpg" />
                <img src="/images/port/av11.jpg" />
                <img src="/images/port/av12.jpg" />
                <img src="/images/port/av13.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo No Controle Série</p>
                </div>
              </div>
            </div>
          </div>

          <div className="ijafs9esd33d ssjddnserr">
            <img className="sadhee231" src="/images/port/avt2.png" />
            <div className="nsakdhe31 niasdf32">
              <h1 className="sceirjfg">GANHOS e RESULTADOS No CONTROLE</h1>

              <p>Por mais incrível que pareça, estar no controle dos ganhos e resultados tem mais haver com a capacidade de se conectar com pessoas do que qualquer outra coisa.</p>
              <p>Comecei a trabalhar com vendas quando ainda era uma menina. Eu não gostava de vender, gostava do resultado que a venda me trazia. Me lembro de não gostar de falar ao telefone e nem saber falar no telefone, mas decidi aprender, quando descobri os ganhos que teria se soubesse fazer isso.</p>
              <p>Com o passar dos anos, entendi que não se tratava de vender... Se tratava de se conectar. Então, desenvolvi algumas habilidades crucialmente importantes para me conectar com pessoas. Aprendi a escutar o que diziam e a me interessar de verdade pelo o que queriam e, aprendi a falar ao coração delas e não apenas a mente.</p>
              <p className="mt-4">Muitos anos depois, passei a ser contratada para dobrar e triplicar os ganhos nas empresas e, depois de passar por mais de 280 negócios de diferentes tamanhos e segmentos, aprendi algumas lições valiosas sobre Empresas e Empresários.
              </p>
              <p>
              Empresas que ganham mais ou que nunca ficam em situações de risco em tempos difíceis são dirigidas por empresários com mentalidade estratégica comercial bem desenvolvida. Agora, as empresas que realmente tinham altos ganhos, seus empresários eram muito habilidosos em se conectar com pessoas: publico, clientes, fornecedores, etc...
              </p>

              <p className="mt-4">
              Se você é mulher e empresária, gostaria de compartilhar com você a melhor notícia de todos os tempos. Você possui poderes e habilidades únicas como: intuição, sensibilidade emocional e, por ter o dom da maternidade, sendo mãe ou não, tem maior capacidade de se conectar e pensar no coletivo. Ser uma líder e se conectar com pessoas está no seu DNA. Portanto, se vendas tem haver com conexão, saber usar e desenvolver esta habilidade para tornar sua empresa fazedora de ganhos e resultados através da conexão é o seu maior desafio.
              </p>
              <p className="mt-4">Se eu consegui, você também consegue. Acredite!</p>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie pt-4 pb-4">
        <div className="container">
          <div className="sdanierhser">
            <h1 className="dsnierg">O MANIFESTO</h1>
            <div className="asdnfsdi"></div>

            <div className="nsdairejrog1sd mt-5">
              <div className="xkdnidr11sds">
                <div>
                  <p className="dsfhkuer">Lista de Espera... INSCREVA-SE!</p>
                </div>
                <div className="d-flex align-items-center">
                  <div>
                    <p className="dsfhkuer sndkne0i4">Semana de Mentoria</p>
                    <p className="dsfhkuer jsdkerr">OnLINE e GRATUITO</p>
                  </div>
                  <img className="eruwherhd" src="/images/arwcrl.png" />
                  <div className="asdfiher-sdw ">
                    <p className="sdrehidf">EU QUERO</p>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="sdafisrjenfd pt-4 pb-4">
        <div className="container">
          <div className="d-flex flex-wrap serhuisdfg justify-content-end">
            <img src="/images/brd/Copia de 1.png" />
            <img src="/images/brd/Copia de 2.png" />
            <img src="/images/brd/Copia de 3.png" />
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <img src="/images/brd/Copia de 4.png" />
            <img src="/images/brd/Copia de 5.png" />
            <img src="/images/brd/Copia de 6.png" />
            <img src="/images/brd/Copia de 7.png" />
            <img src="/images/brd/Copia de 8.png" />
            <img src="/images/brd/Copia de 9.png" />
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <img src="/images/brd/Copia de 10.png" />
            <img src="/images/brd/Copia de 11.png" />
            <img src="/images/brd/Copia de 12.png" />
            <img src="/images/brd/Copia de 13.png" />
            <img src="/images/brd/Copia de 14.png" />
            <img src="/images/brd/Copia de 15.png" />
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <img src="/images/brd/Copia de 16.png" />
            <img src="/images/brd/Copia de 17.png" />
            <img src="/images/brd/Copia de 18.png" />
            <img src="/images/brd/Copia de 19.png" />
            <img src="/images/brd/Copia de 20.png" />
            <img src="/images/brd/Copia de 21.png" />
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <img src="/images/brd/Copia de 21.png" />
            <img src="/images/brd/Copia de 22.png" />
            <img src="/images/brd/Copia de 23.png" />
            <img src="/images/brd/Copia de 24.png" />
            <img src="/images/brd/Copia de 25.png" />
            <img src="/images/brd/Copia de 26.png" />
          </div>
          <div className="d-flex flex-wrap justify-content-center">
            <img src="/images/brd/Copia de 27.png" />
            <img src="/images/brd/Copia de 28.png" />
            <img src="/images/brd/Copia de 29.png" />
            <img src="/images/brd/Copia de 30.png" />
            <img src="/images/brd/Copia de 31.png" />
            <img src="/images/brd/Copia de 32.png" />
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <Footer hasNav={true}/>
    </div>
  );
}
