import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Footer from "../src/components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="asjd9jeaosdih">
        <div className="d-flex justify-content-center flex-column align-items-center">
          <div className="asdaskdjas83he">
            <p>25 Min 18 Seg</p>
          </div>
          <h1>ALTA Performance ou NADA! </h1>
          <h2>Porque este É o Estilo de Vida de quem está No CONTROLE </h2>
        </div>
      </section>

      <section className="aslfjawe9irjeasi">
      <div className="container">
      <div className="d-flex justify-content-around align-items-cente cont sheduewe2">
          <div className="sdfajiow39">
            <img src="/images/avt1.png" alt="img" />
          </div>
          <div className="sdfajiow390-1">
            <div className="asdh83udashn3e">
              <div className="asd8quen9asdjmw">
                <div className="asn9woewa092ojkaskd">
                  <h2>MENTORIA</h2>
                  <img src="/images/stm.png" className="mt-5" alt="img" />
                </div>
              </div>
              <h1>No CONTROLE</h1>
              <p>Você, No Controle da Sua VIDA!</p>
              <div className="ascawuieda8s9h3">
                <img src="/images/sgn.png" alt="img" />
              </div>
            </div>
          </div>
        </div>

      </div>
      
         </section>
         <div className="niokfiecnn2"></div>

      <section className="iu9eqwq0fe">
        
      <div className="asfidko30iskd cont ">
          <div className="sadn893enaw9d23">
            <p>
              <span>NO CONTROLE</span> é um Programa de Mentoria
              <span> para você</span>, que <span>deseja ser</span> plena como
              mulher, empresaria, <span>sendo reconhecida</span> e tendo seus
              <span>objetivos</span> de vida <span>realizados.</span> Que deseja
              nunca mais ter que abrir mão daquilo que é importante. Que quer
              <span>viver as suas prioridades</span> e não apenas viver
              atendendo a prioridade dos outros.
            </p>
            <p>
              E a <span>única maneira</span> de fazer isto
              <span>é estando No Controle</span> aprendendo a
              <span>ter um estilo de vida de Alta Performance!</span>
            </p>
          </div>
          <div className="asfmsrh9wasf pb-4">
            <h2>Início: 14 Jun/21 </h2>
            <img src="/images/arrow.png" alt="img" />
            <div className="znxiwebwwf">
              <p>INSCREVER-ME AGORA NA MENTORIA</p>
            </div>
          </div>
        </div>
   
      </section>
      <section className="bg-gry pb-4">
      <div className="container">
      <div>
          <h4 className="asdnkdffd"> Programa de Mentoria No CONTROLE 4.0</h4>
        </div>
        <div className="row">
          <div className="col-md-6">
            <div>
              <div className="asdhiferr">
                <img className="ajissdsf" src="/images/diary.png"/>
                <p className="masdkere">Planner Exclusivo: 2 PLANNERS enviado para sua casa.
                EDIÇÃO LUXUOSA, ACABAMENTO PREMIUM, COLORIDO COM CAPA DURA.</p>
              </div>
              <div className="asdhiferr">
                <img className="ajissdsf" src="/images/target.png"/>
                <p className="masdkere">Foco no Desenvolvimento de Alta Performance para te colocar No Controle da sua vida. </p>
              </div>
              <div className="asdhiferr">
                <img className="ajissdsf" src="/images/rocket.png"/>
                <p className="masdkere">É o único Programa de Mentoria que utiliza o High Performance PLANNER. Um Acelerador de Resultados para desenvolver novos hábitos, habilidades e crenças promovendo mudança de mentalidade.  
 </p>
              </div>
              <div className="asdhiferr">
                <img className="ajissdsf" src="/images/help.png"/>
                <p className="masdkere">A mentoria é super interativa. Você recebe conteúdo, faz atividades em grupo, tira suas duvidas e aprende a vencer sabotadores com várias técnicas que usa fisiologia e gatilhos.
  
  </p>
              </div>
              <div className="asdhiferr">
                <img className="ajissdsf" src="/images/laddar.png"/>
                <p className="masdkere">Um Método que treina competências específicas para sua mente ter foco no objetivo, vencer a procrastinação, se tornar centrado, desenvolvendo alta performance antes de produtividade direcionando sua mente para ações vitais e não em tarefas.</p>
              </div>
              <div className="asdhiferr">
                <img className="ajissdsf" src="/images/brain.png"/>
                <p className="masdkere">Promove a Mudança de Mentalidade através de práticas simples e diárias baseadas na ciência para reprogramar a mente com mais velocidade – Hora de Ouro.</p>
              </div>
            </div>
          </div>
          <div className="col-md-6">

            <div className="asdfidjer-sd">
              
            </div>

            <div className="nsdairejrog1sd mt-5">
              <img src="/images/arrowpr.png" className="uhruehf" alt="img" />
              <div className="xkdnidr isamfsf">
                <p className="dsfhkuer koasrje">INSCREVER-ME AGORA NA MENTORIA</p>
                <div className="asdfiher-sdw">
                  <p className="sdrehidf">EU QUERO</p>
                </div>
              </div>
            </div>
          </div>
           </div>
      
      </div>
      </section>
      <section className="sanasiseq3osc pt-4 pb-4">
        <div className="amzxcwoea0">
          <img className="asd92jasdias2" src="/images/planners.png" />
          <p className="asdfn93jfasf3sd">+</p>
          <img className="as920icjsfsadw" src="/images/ardown.png" />
          <div className="asd92ksff">
            <h5>Tudo</h5>
            <h5 className="oqwenqwk">Isso</h5>
          </div>
        </div>
      </section>
      <section className="o2wqsasnw pt-4 pb-4">
        <div className="container">
          <div className="d-flex justify-content-end">
            <h2 className="asnkjdowiheausdf niviae9j2">Início: 14 Jun/21</h2>
          </div>
          <div className="row">
            <div className="col-md-9">
              <div>
                <div className="oa0wesbacbbwe asnasijweiasfbs">
                  <img className="qjsdifef123" src="/images/cntrl.png" />
                  <div>
                    <h4 className="asncoajew9osf">VOCÊ, finalmente,</h4>
                    <h4 className="asdi9jasf12f">
                      <span>No CONTROLE</span>
                    </h4>
                    <h4 className="erudshfsdf">da Sua Vida!</h4>
                  </div>
                </div>
                <div className="ja9swejsaqw">
                  <div>
                    <p className="asfniajdwasw ihsdfww2032">
                      COMO FUNCIONA O PROGRAMA DE MENTORIA?
                    </p>
                    <p className="asfaojfsi3e123 ihsdfww20321">
                      Ao adquirir o Programa de Mentoria 4.0 você...
                    </p>
                  </div>
                  <div>
                    <div className="d-flex">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                        Recebe os 2 Planners na sua casa - 1 para cada semestre.
                        <span>
                          EDIÇÃO LUXUOSA ACABAMENTO PREMIUM, COLORIDO COM CAPA
                          DURA.
                        </span>
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                        Aprende passo a passo como usar o planner para construir
                        um estilo de vida de alta performance, treinando sua
                        mente para desenvolver competências e habilidades
                        específicas com práticas simples e objetivas.
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                        É inserido no Grupo Exclusivo para ter acesso a
                        conteúdos, ferramentas e testes para autoavaliação.
                        Responde a um questionário de expectativas.
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                        Recebe um link para participar das mentorias que são
                        online, ao vivo e acontecem 1 vez por semana durante 3
                        meses - 90 dias, 90 minutos por encontro.
                      </p>
                    </div>
                    <div className="d-flex mt-2">
                      <img
                        className="asfines11sd mt-1"
                        src="/images/check.png"
                      />
                      <p className="asfaojfsi3e osif9eu-we9e">
                        Você pode e deve participar tirando dúvidas diretamente
                        comigo, Elis Ferraz, durante as mentorias ou com a
                        equipe de co-facilitadores.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="d-flex justify-content-end flex-column align-items-end ih9qweqwncsae">
                  <div>
                    <h5 className="asdniejsfwqe">
                      O MAIOR <span>BÔNUS</span>
                    </h5>
                    <h5 className="uhteahdg">da Sua Vida!</h5>
                    <img
                      className="asdf3jej0sawe"
                      src="/images/arrow-dwn.png"
                    />
                  </div>
                </div>
                <div className="d-flex naskerer">
                  <img className="ii29sna2hds922d" src="/images/oplaner.png" />
                  <div className="hriehudfdg">
                    <p className="asfniajdwasw">O PLANNER</p>
                    <p className="eowujsdifhsdg">
                      EDIÇÃO LUXUOSA, ACABAMENTO PREMIUM, COLORIDO COM CAPA
                      DURA.
                    </p>
                    <p className="nasidfasdnsfndsje">
                      É o primeiro Planner no mundo com esta proposta de Estilo
                      de Vida de Alta Performance. O High Performance Planner é
                      um novo conceito e um novo estilo de vida de pessoas que
                      querem estar No Controle. Foi desenvolvido para que, com
                      menos esforço se tenha resultados extraordinários,
                      promovendo Alta Performance e acelerando resultados. Um
                      novo conceito baseado no que há de mais atual na ciência
                      da mente que, através de ações simples, práticas e
                      objetivas promove a mudança de mentalidade criando uma
                      experiência única reprogramando sua mente para vencer.
                    </p>
                  </div>
                </div>
                <div className="asj9awirjfsdfdge">
                  <img
                    className="ewkaosfer ihbwibcvw"
                    src="/images/arrow.png"
                    alt="img"
                  />
                  <div className="znxiwebwwf">
                    <p className="jeure">INSCREVER-ME AGORA NA MENTORIA</p>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-3">
              <div className="mt-5">
                <div className="ndskfiere">
                  <img src="/images/key.png" />
                  <div className="">
                    <p className="weorweietdf">
                      3 meses,12 mentorias, 90 dias, 90 minutos cada.
                    </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/face.png" />
                  <div className="">
                    <p className="weorweietdf">
                      3 meses,12 mentorias, 90 dias, 90 minutos cada.
                    </p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <div>
                    <img src="/images/cam.png" />
                    <img src="/images/mic.png" />
                  </div>

                  <div className="">
                    <p className="weorweietdf">Mentoria Ao Vivo e Interativa</p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <img src="/images/booksm.png" />
                  <div className="">
                    <p className="weorweietdf">Vídeo Aulas e PodCas.</p>
                  </div>
                </div>

                <div className="ndskfiere">
                  <img src="/images/chat.png" />
                  <div className="">
                    <p className="weorweietdf">
                      Testes de Comportamento, PDFs e Ferramentas
                    </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/lock.png" />
                  <div className="">
                    <p className="weorweietdf">
                      Equipe de Suporte e encontros comigo.
                    </p>
                  </div>
                </div>
                <div className="ndskfiere">
                  <img src="/images/qr.png" />
                  <div className="">
                    <p className="weorweietdf">
                      Grupo Exclusivo de Mentoria, atividade dupla.
                      complementares
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie nmsdfeur">
        <div className="container">
          <div className="row">
            <div className="col-md-5">
              <div className="h23iasfwe2323">
              <p className="nasdfiwnf1 ouirwc-a9wej">
                Este <span>Programa</span>
              </p>
              <p className="nasdfiwnf ouirwc-a9wej">
                de <span>Mentoria</span> é para
              </p>
              <p className="nasdfiwnf1 ouirwc-a9wej"> VOCÊ QUE...</p>
             
              </div>
              <div className="asdfkhasiddeg">
                <img className="jaiodfie9r23" src="/images/fotoelis.png" />
              </div>
            </div>
            <div className="col-md-7">
              <div>
                <div className="sandoasfjasuw">
                  <p>
                    QUE NÃO SE SENTE NO CONTROLE. QUE PARECE QUE VIVE A VIDA
                    PARA OS OUTROS E MAL TE SOBRA TEMPO PRA CUIDAR DE VOCÊ.
                  </p>
                </div>
                <div className="sandoasfjasuw">
                  <p>
                    QUE ESTÁ CANSADA DE ESCOLHER ENTRE A VIDA PESSOAL E O SEU
                    NEGÓCIO.
                  </p>
                </div>

                <div className="sandoasfjasuw">
                  <p>
                    QUE SE SENTE FRUSTRADA POR NÃO CONSEGUIR DAR CONTA DE TUDO O
                    QUE É IMPORTANTE PRA VOCÊ.
                  </p>
                </div>

                <div className="sandoasfjasuw">
                  <p>
                    QUE SE SENTE FRUSTRADA POR NÃO CONSEGUIR DAR CONTA DE TUDO O
                    QUE É IMPORTANTE PRA VOCÊ.
                  </p>
                </div>

                <div className="sandoasfjasuw">
                  <p>
                    QUE QUER VIVER UMA VIDA PLENA SENDO MULHER, EMPRESÁRIA, MÃE,
                    ESPOSA E SER RECONHECIDA PROFISSIONALMENTE.
                  </p>
                </div>
              </div>
              <div className="nsdairejrog mt-5">
                <img src="/images/arrowpr.png" alt="img" />
                <div className="asndfiwhsefgg">
                  <p>ESTA MENTORIA É PARA MIM</p>
                </div>
                <img src="/images/arrowpl.png" alt="img" />
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="esfhdjfsje pb-4">
        <div className="d-flex msdjnjeber">
          <h1 className="asdfnjk3rdfge34">3</h1>
          <div className="nsareur">
            <h2 className="asdf3jirsekg3">Motivos</h2>
            <h2 className="eirddsage iieorhjofd ojof0-12f">PARA VOCÊ INICIAR</h2>
            <h2 className="enndgsdaer hidferifer">A JORNADA DE</h2>
            <h2 className="isdnsdier">Mudança de MENTALIDADE</h2>
          </div>
        </div>

        <div className="nasklfnawrfg">
          <div className="nakskfawjrojasfg">
            <img className="bsjdfsert" src="/images/trgbig.png" />
            <div className="jfsdkljrt">
              <p>Você é o que você pensa.</p>
              <p>Se você não mudar sua mentalidade, vai continuar</p>
              <p>
                <span>tendo essa vida</span> que você
                <span>já não quer mais.</span>
              </p>
            </div>
          </div>
          <div className="nakskfawjrojasfg">
            <img className="bsjdfsert" src="/images/trgbig.png" />
            <div className="jfsdkljrt">
              <p>
                Essa é a <span>única maneira</span> de estar No Controle.
              </p>
              <p>
                A verdade é que <span>se você não está no controle</span>
              </p>
              <p>
                da sua vida, <span>então você está sendo controlada.</span>
              </p>
            </div>
          </div>
          <div className="nakskfawjrojasfg">
            <img className="bsjdfsert" src="/images/trgbig.png" />
            <div className="jfsdkljrt">
              <p>
                <span>Ter um estilo de vida</span> de
                <span>Alta Performance é</span>
              </p>
              <p>
                o que <span>pessoas inteligentes fazem.</span>
              </p>
              <p>Você pode escolher não fazer a mentoria por medo </p>
              <p>de arriscar... Mas se não arriscar por tão pouco, nunca</p>
              <p>saberá como é estar do outro lado.</p>
            </div>
          </div>
        </div>

        <div className="nsdairejrog mt-5">
          <img src="/images/arrowpr.png" alt="img" />
          <div className="asndfiwhsefgg">
            <p>ESTA MENTORIA É PARA MIM</p>
          </div>
          <img src="/images/arrowpl.png" alt="img" />
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie pt-4 pb-4">
        <div className="container pt-5">
          <div className="hdsjaferur d-flex justify-content-center align-items-center">
            <div>
              <img className="asfbaorniafine" src="/images/seal.png" />
            </div>
            <div className="rithsreg">
              <p>
                Este Programa de Mentoria é baseado em princípeios atemporais,
                governantes, objetivos e universais. Não importa em que época ou
                periodo da vida você esteja, eles sempre vão promover as
                mudanças necessárias na sua vida.
              </p>
              <p>
                Por isso decidi que você terá acesso ao conteúdo e novas aulas
                para sempre e poderá adquirir NOVOS PLANNERS sempre que desejar.
              </p>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bg-theme pb-4">
        <div className="container pt-5">
          <div className="d-flex justify-content-center align-items-center flex-column">
            <div className="d-flex jadsre9cjm">
              <h1 className="zxehdfkr">5</h1>
              <div className="asdurkfe">
                <h2 className="dtruxfgf">Bônus</h2>
                <h2 className="weisfng">EXCLUSIVOS</h2>
                <h2 className="dtruxfgf">Para VOCÊ.</h2>
              </div>
            </div>

            <div className="d-flex flex-wrap justify-content-center">
              <div className="ejkdhse">
                <h1>BÔNUS #1</h1>
                <img src="/images/bubble.png" />
                <p>ACESSO</p>
                <p>DIRETO COMIGO, </p>
                <p>ELIS FERRAZ, ONLINE.</p>
              </div>
              <div className="ejkdhse">
                <h1>BÔNUS #2</h1>
                <img src="/images/play.png" />
                <p>ACESSO as </p>
                <p>GRAVAÇÕES das</p>
                <p>MENTORIAS ao VIVO.</p>
              </div>
              <div className="ejkdhse">
                <h1>BÔNUS #3</h1>
                <img src="/images/comunity.png" />
                <p>PARTICIPAR</p>
                <p>GRUPO EXCLUSIVO</p>
                <p>“TRIBO NO CONTROLE”</p>
                <p>Facebook</p>
              </div>
              <div className="ejkdhse">
                <h1>BÔNUS #4</h1>
                <img src="/images/video.png" />
                <p>VOUCHER de ACESSO </p>
                <p>PARA MENTORIAS </p>
                <p>ALAVANCAR e </p>
                <p>GANHAR MAIS.</p>
              </div>
              <div className="ejkdhse">
                <h1>BÔNUS #5</h1>
                <img src="/images/tickets.png" />
                <p>INGRESSO</p>
                <p>RALLY 2022 - OnLine</p>
                <p>NO CONTROLE</p>
              </div>
            </div>
            <div className="nsdairejrog mt-5">
              <img src="/images/arrow.png" alt="img" />
              <div className="asndfiwhsefgg11">
                <p>INSCREVER-ME AGORA NA MENTORIA</p>
              </div>
              <img src="/images/arrowl.png" alt="img" />
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie pt-5 pb-4">
        <div className="container">
          <div className="xjbzeefb">
            <h1>NÓS ACREDITAMOS em Elis Ferraz!</h1>
            <div className="klgjt">
              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Rachel França</p>
                    <span>Empresária | Arquiteta</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “Aprender a atitude certa, desenvolvendo Alta Performance me
                  fez decolar na vida!”
                </p>
              </div>

              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Isis Leal</p>
                    <span>Empresária | Teatro</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “A mudança de Mentalidade é a chave para alavancar na vida e
                  nos negócios!”
                </p>
              </div>

              <div className="xjbzeefb m-3">
                <div className="weonksfi">
                  <img src="/images/scr.png" />
                  <div className="airyew3oif">
                    <p>Mel Domezi</p>
                    <span>Empresária</span>
                  </div>
                </div>
                <p className="sajjksdue">
                  “A transformação do meu jeito de pensar, me fez conquistar
                  muito, incluive fontes de renda!”
                </p>
              </div>
            </div>
            <div className="nsdairejrog1sd mt-5">
              <img src="/images/arrowpr.png" className="uhruehf" alt="img" />
              <div className="xkdnidr">
                <p className="dsfhkuer">ESTA MENTORIA É PARA MIM</p>
                <img src="/images/arwcrl.png" />
                <div className="asdfiher-sdw">
                  <p className="sdrehidf">EU QUERO</p>
                </div>
              </div>
              <img src="/images/arrowpl.png" className="uhruehf" alt="img" />
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bg-gry pt-4 pb-4">
        <div className="container">
          <div className="d-flex justify-content-center">
            <img className="nadfmnrueyr" src="/images/ardown.png" />
            <div className="nsdfjuce">
              <h1>Valor Oficial</h1>
              <div className="oj910wsadwe-21sa">
              <div className="d-flex justify-content-center align-items-center">
                <img src="/images/trgbig.png" />
                <p>
                  
                  <span>À</span> vista <span className="ojojiasq039">R$</span> 2.997,00
                </p>
              </div>
              <div className="d-flex justify-content-center align-items-center">
                <img src="/images/trgbig.png" />
                <p>
                  
                  <span>03</span> <span className="ojojiasq039">X sem Juros de R$ 999,00</span>
                </p>
                
              </div>
              <div className="d-flex justify-content-center align-items-center">
                <img src="/images/trgbig.png" />
                <p>
                  
                  <span>12</span> <span className="ojojiasq039">X de R$ 299,70</span>
                </p>
              </div>
           
              </div>
           
            </div>
            <img className="nadfmnrueyr" src="/images/ardown2.png" />
          </div>
          <div className="nisfmqwds-qw knsvduer">
            <div className="xcnvjrusdf">
              <h1>OFERTA Especial</h1>
              <p>R$ 1.997,00</p>
              <p>12 x R$ 199,70</p>
            </div>
            <div className="nvksjer">
              <div>
                <p>
                  <span>2 Dias 7h 20 min</span>
                </p>
              </div>
            </div>
          </div>

          <div>
            <div className="nsdairejrog mt-3 mb-5">
              <img src="/images/arrowpr.png" alt="img" />
              <div className="paddsdanier asndfiwhsefgg">
                <p className="">QUERO ESTA OFERTA</p>
              </div>
              <img src="/images/arrowpl.png" alt="img" />
            </div>
          </div>

          <div className="zxnvuer d-flex">
            <div className="xjfudfsdi m-auto">
              <h1>Eu</h1>
              <h2>ACREDITO</h2>
              <h2>Em VOCÊ</h2>
            </div>
            <div className="nsdjfrihf">
              <h1>Eu ACREDITO</h1>
              <p>
                Nas pessoas. Sei que elas podem mudar seus resultados se mudarem
                o jeito de pensar.
              </p>
              <p>
                Acredito que, a transformação de uma pessoa, pode significar
                relacionamentos mais bem sucedidos, filhos mais fortes e
                famílias mais unida.
              </p>
              <p>
                Acredito na reprogramação da mente baseada na ciência. E ela
                pode ser conquistada com pequenas ações diárias.
              </p>
              <p>
                Acredito que o mundo se torna um lugar melhor quando ajuda
                pessoas a transformarem suas vidas.
              </p>
              <p>
                Acredito em tudo isso, porque tive que por a prova todas essas
                crenças diante dos desafios que enfrentei ao longo da minha
                vida. Estar No Controle foi o que me garantiu o sucesso e o que
                tem garantido o sucesso de todos os que vivem essa experiência.
              </p>
              <h3>ELIS FERRAZ</h3>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="o2wqsasnw pt-4 pb-4">
        <div className="container">
          <div className="snafjrjifjg">
            <div className="row">
              <div className="col-md-6">
                <div>
                  <img className="nisetje" src="/images/fotoelis.png" />
                  <div className="jfaewisf">
                    <p className="agdhgegg">ELIS FERRAZ</p>
                    <div className="sdfgjiet"></div>
                  </div>
                </div>
              </div>
              <div className="col-md-6">
                <div className="czxbvdsuf">
                  <h1>Quem</h1>
                  <h6>será sua </h6>
                  <h2>MENTORA e</h2>
                  <h2>Treinadora ?</h2>
                </div>
              </div>
            </div>
            <div>
              <p className="dfjaier">
                Elis é empresária há mais de 17 anos. Passou por mais de 280
                empresas atuando em estratégias, gestão comercial, contratação,
                desenvolvimento de pessoas e de mentalidade de alta performance.
              </p>
            </div>

            <div className="gsdjhrgy">
              <h2>EMPRESÁRIA</h2>
              <div className="d-flex asfnsoirr3-23">
                <span>+</span>
                <h5> 17 anos de experiência</h5>
              </div>
            </div>
            <div className="gsdjhrgy asfosjr-seew">
              <h2>MENTORA E TREINADORA</h2>
              <div className="d-flex asfnsoirr3-23">
                <span>+</span>
                <h5> 2.000 pessoas Treinadas e mais de 280 empresas </h5>
              </div>
            </div>
            <div className="gsdjhrgy asfosjr-seew">
              <h2>Author</h2>
              <div className="m-0 d-flex asfnsoirr3-23">
                <span className="nsirefg">+</span>
                <h5>
                  
                  15 programas de treinamentos, entre eles: 10em1 - 10 anos de
                  Faturamento em 1; 6 Super Habilidades - Influenciar | Escolher
                  | Escutar | Conversar | Negociar | Liderar; Programas de
                  Mentoria para empresas e empresários - No Controle | Alavancar
                  | Ganhar Mais.
                </h5>
              </div>
            </div>
          </div>
          <div className="cmdsfnief">
            <div>
              <img className="kndgofdg" src="/images/cloud.png" />
              <img className="sfdghidgr" src="/images/exam.png" />
            </div>
            <div className="ariothge">
              <div className="asfmsrh9wasf">
                <div className="znxiwebwwf">
                  <p className="sandsket">INSCREVER-ME AGORA NA MENTORIA</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bgpajsfie pt-4 pb-4">
        <div className="container">
          <div className="sdanierhser">
            <h1 className="dsnierg">O MANIFESTO</h1>
            <div className="asdnfsdi"></div>

            <div className="nsdairejrog1sd mt-5">
              <div className="xkdnidr">
                <div className="d-flex flex-column">
                  <p className="dsfhkuer">Estar No Controle Agora!</p>
                  <p className="dsfhkuer text-center">INSCREVER-ME</p>
                </div>
                <img src="/images/arwcrl.png" />
                <div className="asdfiher-sdw">
                  <p className="sdrehidf">EU QUERO</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="bg-gry-1s pt-4 pb-4">
        <div className="container">
          <div>
            <h1 className="ndsajfsdfer">ELIS Pra VOCÊ!</h1>
            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av2.jpg" />
                <img src="/images/port/av3.jpg" />
                <img src="/images/port/av4.jpg" />
                <img src="/images/port/av5.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo Minha História</p>
                </div>
              </div>
            </div>

            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av6.jpg" />
                <img src="/images/port/av7.jpg" />
                <img src="/images/port/av8.jpg" />
                <img src="/images/port/av9.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo Sou Mulher Série</p>
                </div>
              </div>
            </div>

            <div className="">
              <div className="nsdkfhe sfeoireork">
                <img src="/images/port/av10.jpg" />
                <img src="/images/port/av11.jpg" />
                <img src="/images/port/av12.jpg" />
                <img src="/images/port/av13.jpg" />
                <div className="asjdiwefer">
                  <p className="sdjaojer"> Vídeo No Controle Série</p>
                </div>
              </div>
            </div>
          </div>

          <div className="sdnserr i9ehdh283dcd">
            <img className="sadhee" src="/images/port/av1.png" />
            <div className="nsakdhe3 ihsa92wocns2">
              <h1 className="sceirjfg">EU, O PLANNER e uma Vida No CONTROLE</h1>

              <p>
                Você já pensou o que te faz realizar uma grande mudança? 
              </p>
              <p>Para
                mim, foi estar entre a vida e a morte.</p>
              <p>
                Me tornei uma mulher bem sucedida, mas quando vieram os filhos e
                as responsabilidades com a família aumentaram, passei a ter que
                escolher entre ser empresária e ter uma família. Foram os anos
                mais difíceis de minha vida!
              </p>
              <p>
                O problema não era ter que conciliar a empresa e a família, era
                conciliar essas duas coisas que eu considerava uma prioridade
                tentando ser produtiva ao invés de estratégica sendo uma mulher
                de Alta Performance.
              </p>

              <p>
                Eu aprendi a estar No Controle da minha vida deixando de usar os
                modelos de produtividade criado para homens e por homens. Passei
                a adotar uma nova abordagem, fazendo as coisas do jeito mulher,
                aprendendo a colocar “Energia Certa no Lugar exato”. E dessa
                forma, acelerei meus resultados e passei a viver uma vida de
                muitas conquistas.
              </p>
              <p>A vida é um espelho que me reflete e eu gosto do que vejo!</p>
            </div>
          </div>
      
      
        </div>
      </section>
      <div className="niokfiecnn2"></div>

      <section className="sdafisrjenfd pt-4 pb-4">
        <div className="container">
        <div className="d-flex flex-wrap serhuisdfg justify-content-end">
          <img src="/images/brd/Copia de 1.png"/>
          <img src="/images/brd/Copia de 2.png"/>
          <img src="/images/brd/Copia de 3.png"/>
          
        </div>
        <div className="d-flex flex-wrap justify-content-center">
          <img src="/images/brd/Copia de 4.png"/>
          <img src="/images/brd/Copia de 5.png"/>
          <img src="/images/brd/Copia de 6.png"/>
          <img src="/images/brd/Copia de 7.png"/>
          <img src="/images/brd/Copia de 8.png"/>
          <img src="/images/brd/Copia de 9.png"/>
        </div>
        <div className="d-flex flex-wrap justify-content-center">
          <img src="/images/brd/Copia de 10.png"/>
          <img src="/images/brd/Copia de 11.png"/>
          <img src="/images/brd/Copia de 12.png"/>
          <img src="/images/brd/Copia de 13.png"/>
          <img src="/images/brd/Copia de 14.png"/>
          <img src="/images/brd/Copia de 15.png"/>
        </div>
        <div className="d-flex flex-wrap justify-content-center">
          <img src="/images/brd/Copia de 16.png"/>
          <img src="/images/brd/Copia de 17.png"/>
          <img src="/images/brd/Copia de 18.png"/>
          <img src="/images/brd/Copia de 19.png"/>
          <img src="/images/brd/Copia de 20.png"/>
          <img src="/images/brd/Copia de 21.png"/>
        </div>
        <div className="d-flex flex-wrap justify-content-center">
          <img src="/images/brd/Copia de 21.png"/>
          <img src="/images/brd/Copia de 22.png"/>
          <img src="/images/brd/Copia de 23.png"/>
          <img src="/images/brd/Copia de 24.png"/>
          <img src="/images/brd/Copia de 25.png"/>
          <img src="/images/brd/Copia de 26.png"/>
        </div>
        <div className="d-flex flex-wrap justify-content-center">
          <img src="/images/brd/Copia de 27.png"/>
          <img src="/images/brd/Copia de 28.png"/>
          <img src="/images/brd/Copia de 29.png"/>
          <img src="/images/brd/Copia de 30.png"/>
          <img src="/images/brd/Copia de 31.png"/>
          <img src="/images/brd/Copia de 32.png"/>
        </div>
        </div>
      </section>

      <Footer hasNav={true}/>

    </div>
  );
}
